{"name": "test_api[args1]", "status": "failed", "statusDetails": {"message": "Failed: Fixture \"assert_handle\" called directly. Fixtures are not meant to be called directly,\nbut are created automatically when test functions request them as parameters.\nSee https://docs.pytest.org/en/stable/fixture.html for more information about fixtures, and\nhttps://docs.pytest.org/en/stable/deprecations.html#calling-fixtures-directly about how to update your code.", "trace": "Fixture \"assert_handle\" called directly. Fixtures are not meant to be called directly,\nbut are created automatically when test functions request them as parameters.\nSee https://docs.pytest.org/en/stable/fixture.html for more information about fixtures, and\nhttps://docs.pytest.org/en/stable/deprecations.html#calling-fixtures-directly about how to update your code."}, "description": "遍历每一个yaml测试用例集", "parameters": [{"name": "args", "value": "{'name': '登录接口', 'request': {'method': 'post', 'url': 'http://47.114.189.49:8000/sso/login/password', 'data': {'password': 'E10ADC3949BA59ABBE56E057F20F883E', 'phone': '18800000020', 'platform': 'Test'}, 'headers': {'token': 1}}, 'assert_code': 1, 'vaildate': {'eq': {'signature': '南风知我意'}}}"}], "start": 1628150686423, "stop": 1628150686505, "uuid": "6279995a-d3b9-422c-baa2-cd7233fa291b", "historyId": "ada54e6eaca6b5d210bb37e1ddd5f116", "testCaseId": "549118e0bc894b5383b4db3137574d51", "fullName": "testcase.test_api.TestApi#test_api", "labels": [{"name": "tag", "value": "@pytest.mark.usefixtures('set_up')"}, {"name": "parentSuite", "value": "testcase"}, {"name": "suite", "value": "test_api"}, {"name": "subSuite", "value": "TestApi"}, {"name": "host", "value": "DESKTOP-TP47VI7"}, {"name": "thread", "value": "4480-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testcase.test_api"}]}