{"name": "test_api[args2]", "status": "failed", "statusDetails": {"message": "Failed: Fixture \"assert_handle\" called directly. Fixtures are not meant to be called directly,\nbut are created automatically when test functions request them as parameters.\nSee https://docs.pytest.org/en/stable/fixture.html for more information about fixtures, and\nhttps://docs.pytest.org/en/stable/deprecations.html#calling-fixtures-directly about how to update your code.", "trace": "Fixture \"assert_handle\" called directly. Fixtures are not meant to be called directly,\nbut are created automatically when test functions request them as parameters.\nSee https://docs.pytest.org/en/stable/fixture.html for more information about fixtures, and\nhttps://docs.pytest.org/en/stable/deprecations.html#calling-fixtures-directly about how to update your code."}, "description": "遍历每一个yaml测试用例集", "parameters": [{"name": "args", "value": "{'name': '获取个人信息接口', 'request': {'method': 'get', 'url': 'http://47.114.189.49:8000/member/info', 'data': None, 'headers': {'token': 0}}, 'assert_code': 1, 'vaildate': {'eq': {'signature': '南风知我意', 'money': 0.0, 'showTime': 2000}}}"}], "start": 1628150686528, "stop": 1628150686599, "uuid": "0baa3905-199c-4a8a-b6a2-e76de17a74c8", "historyId": "b653b2e781fcca7ae50b2775c21f20f9", "testCaseId": "549118e0bc894b5383b4db3137574d51", "fullName": "testcase.test_api.TestApi#test_api", "labels": [{"name": "tag", "value": "@pytest.mark.usefixtures('set_up')"}, {"name": "parentSuite", "value": "testcase"}, {"name": "suite", "value": "test_api"}, {"name": "subSuite", "value": "TestApi"}, {"name": "host", "value": "DESKTOP-TP47VI7"}, {"name": "thread", "value": "4480-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testcase.test_api"}]}