{"name": "test_api[args0]", "status": "failed", "statusDetails": {"message": "Failed: Fixture \"assert_handle\" called directly. Fixtures are not meant to be called directly,\nbut are created automatically when test functions request them as parameters.\nSee https://docs.pytest.org/en/stable/fixture.html for more information about fixtures, and\nhttps://docs.pytest.org/en/stable/deprecations.html#calling-fixtures-directly about how to update your code.", "trace": "Fixture \"assert_handle\" called directly. Fixtures are not meant to be called directly,\nbut are created automatically when test functions request them as parameters.\nSee https://docs.pytest.org/en/stable/fixture.html for more information about fixtures, and\nhttps://docs.pytest.org/en/stable/deprecations.html#calling-fixtures-directly about how to update your code."}, "description": "遍历每一个yaml测试用例集", "parameters": [{"name": "args", "value": "{'name': '获取首页帖子列表', 'request': {'method': 'get', 'url': 'http://47.114.189.49:8000/post', 'data': {'pageNum': 1, 'pageSize': 10}, 'headers': {'token': 1}}, 'assert_code': 0, 'vaildate': {'eq': {'mainTitle': '100'}}}"}], "start": 1628150686338, "stop": 1628150686423, "uuid": "5c0c08d7-28e8-4f8c-991a-0b01e31f6343", "historyId": "5bf739e561c362dc592a2aa6a14e195b", "testCaseId": "549118e0bc894b5383b4db3137574d51", "fullName": "testcase.test_api.TestApi#test_api", "labels": [{"name": "tag", "value": "@pytest.mark.usefixtures('set_up')"}, {"name": "parentSuite", "value": "testcase"}, {"name": "suite", "value": "test_api"}, {"name": "subSuite", "value": "TestApi"}, {"name": "host", "value": "DESKTOP-TP47VI7"}, {"name": "thread", "value": "4480-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testcase.test_api"}]}