[2021-09-17 13:48:20,631] - logger.py] - INFO: --------接口自动化测试开始------------
[2021-09-17 13:48:20,631] - logger.py] - INFO: caseName: <新增集团（启用状态）>
[2021-09-17 13:48:21,218] - logger.py] - ERROR: {"code":1,"msg":"手机号码已存在!","data":1}
[2021-09-17 13:48:21,224] - logger.py] - INFO: caseName: <客户集团基础信息编辑>
[2021-09-17 13:48:21,242] - logger.py] - ERROR: {"code":1,"msg":"手机号码已存在!","data":1}
[2021-09-17 13:48:21,247] - logger.py] - INFO: caseName: <禁用-启用 客户集团信息>
[2021-09-17 13:48:21,249] - logger.py] - ERROR: {"code":1,"msg":"手机号码已存在!","data":1}
[2021-09-17 13:48:21,255] - logger.py] - INFO: caseName: <删除 客户集团信息>
[2021-09-17 13:48:21,257] - logger.py] - ERROR: {"code":1,"msg":"手机号码已存在!","data":1}
[2021-09-17 13:48:21,259] - logger.py] - INFO: caseName: <展示客户列表>
[2021-09-17 13:48:22,534] - logger.py] - ERROR: {"code":1,"msg":null,"data":null}
[2021-09-17 13:48:22,536] - logger.py] - INFO: --------接口自动化测试结束------------
[2021-09-17 13:49:51,445] - logger.py] - INFO: --------接口自动化测试开始------------
[2021-09-17 13:49:51,445] - logger.py] - INFO: caseName: <新增集团（启用状态）>
[2021-09-17 13:49:52,239] - logger.py] - INFO: 断言结果：pass (0 == 0)
[2021-09-17 13:49:52,313] - logger.py] - ERROR: {"code":0,"msg":null,"data":true}
[2021-09-17 13:49:52,319] - logger.py] - INFO: caseName: <客户集团基础信息编辑>
[2021-09-17 13:49:52,320] - logger.py] - ERROR: {"code":0,"msg":null,"data":true}
[2021-09-17 13:49:52,326] - logger.py] - INFO: caseName: <禁用-启用 客户集团信息>
[2021-09-17 13:49:52,328] - logger.py] - ERROR: {"code":0,"msg":null,"data":true}
[2021-09-17 13:49:52,333] - logger.py] - INFO: caseName: <删除 客户集团信息>
[2021-09-17 13:49:52,335] - logger.py] - ERROR: {"code":0,"msg":null,"data":true}
[2021-09-17 13:49:52,339] - logger.py] - INFO: caseName: <展示客户列表>
[2021-09-17 13:49:53,313] - logger.py] - ERROR: {"code":1,"msg":null,"data":null}
[2021-09-17 13:49:53,315] - logger.py] - INFO: --------接口自动化测试结束------------
[2021-09-17 13:52:33,228] - logger.py] - INFO: --------接口自动化测试开始------------
[2021-09-17 13:52:33,229] - logger.py] - INFO: caseName: <新增集团（启用状态）>
[2021-09-17 13:52:33,633] - logger.py] - ERROR: {"code":1,"msg":"手机号码已存在!","data":1}
[2021-09-17 13:52:33,638] - logger.py] - INFO: caseName: <客户集团基础信息编辑>
[2021-09-17 13:52:33,640] - logger.py] - ERROR: {"code":1,"msg":"手机号码已存在!","data":1}
[2021-09-17 13:52:33,645] - logger.py] - INFO: caseName: <禁用-启用 客户集团信息>
[2021-09-17 13:52:33,647] - logger.py] - ERROR: {"code":1,"msg":"手机号码已存在!","data":1}
[2021-09-17 13:52:33,649] - logger.py] - INFO: caseName: <删除 客户集团信息>
[2021-09-17 13:52:33,650] - logger.py] - ERROR: {"code":1,"msg":"手机号码已存在!","data":1}
[2021-09-17 13:52:33,653] - logger.py] - INFO: caseName: <禁用-启用 客户集团信息>
[2021-09-17 13:52:33,654] - logger.py] - ERROR: {"code":1,"msg":"手机号码已存在!","data":1}
[2021-09-17 13:52:33,655] - logger.py] - INFO: --------接口自动化测试结束------------
[2021-09-17 13:54:21,599] - logger.py] - INFO: --------接口自动化测试开始------------
[2021-09-17 13:54:21,599] - logger.py] - INFO: caseName: <新增集团（启用状态）>
[2021-09-17 13:54:22,192] - logger.py] - INFO: 断言结果：pass (0 == 0)
[2021-09-17 13:54:22,248] - logger.py] - ERROR: {"code":0,"msg":null,"data":true}
[2021-09-17 13:54:22,254] - logger.py] - INFO: caseName: <客户集团基础信息编辑>
[2021-09-17 13:54:22,256] - logger.py] - ERROR: {"code":0,"msg":null,"data":true}
[2021-09-17 13:54:22,261] - logger.py] - INFO: caseName: <禁用-启用 客户集团信息>
[2021-09-17 13:54:22,264] - logger.py] - ERROR: {"code":0,"msg":null,"data":true}
[2021-09-17 13:54:22,269] - logger.py] - INFO: caseName: <删除 客户集团信息>
[2021-09-17 13:54:22,271] - logger.py] - ERROR: {"code":0,"msg":null,"data":true}
[2021-09-17 13:54:22,276] - logger.py] - INFO: caseName: <禁用-启用 客户集团信息>
[2021-09-17 13:54:22,278] - logger.py] - ERROR: {"code":0,"msg":null,"data":true}
[2021-09-17 13:54:22,278] - logger.py] - INFO: --------接口自动化测试结束------------
[2021-09-17 13:55:04,272] - logger.py] - INFO: --------接口自动化测试开始------------
[2021-09-17 13:55:04,273] - logger.py] - INFO: caseName: <新增集团（启用状态）>
[2021-09-17 13:55:04,811] - logger.py] - INFO: 断言结果：pass (0 == 0)
[2021-09-17 13:55:04,922] - logger.py] - INFO: caseName: <客户集团基础信息编辑>
[2021-09-17 13:55:04,928] - logger.py] - INFO: caseName: <禁用-启用 客户集团信息>
[2021-09-17 13:55:04,933] - logger.py] - INFO: caseName: <删除 客户集团信息>
[2021-09-17 13:55:04,939] - logger.py] - INFO: caseName: <禁用-启用 客户集团信息>
[2021-09-17 13:55:04,943] - logger.py] - INFO: --------接口自动化测试结束------------
[2021-09-17 13:56:13,475] - logger.py] - INFO: --------接口自动化测试开始------------
[2021-09-17 13:56:13,476] - logger.py] - INFO: caseName: <新增集团（启用状态）>
[2021-09-17 13:56:13,751] - logger.py] - INFO: caseName: <客户集团基础信息编辑>
[2021-09-17 13:56:13,904] - logger.py] - INFO: caseName: <禁用-启用 客户集团信息>
[2021-09-17 13:56:14,225] - logger.py] - INFO: caseName: <删除 客户集团信息>
[2021-09-17 13:56:14,537] - logger.py] - INFO: 断言结果：pass (0 == 0)
[2021-09-17 13:56:14,542] - logger.py] - INFO: caseName: <禁用-启用 客户集团信息>
[2021-09-17 13:56:14,937] - logger.py] - INFO: --------接口自动化测试结束------------
[2021-09-17 13:56:59,697] - logger.py] - INFO: --------接口自动化测试开始------------
[2021-09-17 13:56:59,698] - logger.py] - INFO: caseName: <新增集团（启用状态）>
[2021-09-17 13:57:00,317] - logger.py] - INFO: 断言结果：pass (0 == 0)
[2021-09-17 13:57:00,435] - logger.py] - INFO: caseName: <客户集团基础信息编辑>
[2021-09-17 13:57:00,538] - logger.py] - INFO: caseName: <禁用-启用 客户集团信息>
[2021-09-17 13:57:00,814] - logger.py] - INFO: caseName: <删除 客户集团信息>
[2021-09-17 13:57:01,137] - logger.py] - INFO: 断言结果：pass (0 == 0)
[2021-09-17 13:57:01,141] - logger.py] - INFO: caseName: <禁用-启用 客户集团信息>
[2021-09-17 13:57:01,424] - logger.py] - INFO: --------接口自动化测试结束------------
[2021-09-17 13:58:46,335] - logger.py] - INFO: --------接口自动化测试开始------------
[2021-09-17 13:58:46,335] - logger.py] - INFO: caseName: <新增集团（启用状态）>
[2021-09-17 13:58:47,005] - logger.py] - INFO: 断言结果：pass (0 == 0)
[2021-09-17 13:58:47,071] - logger.py] - INFO: caseName: <客户集团基础信息编辑>
[2021-09-17 13:58:47,257] - logger.py] - INFO: caseName: <禁用-启用 客户集团信息>
[2021-09-17 13:58:47,531] - logger.py] - INFO: 断言结果：pass (0 == 0)
[2021-09-17 13:58:47,534] - logger.py] - INFO: caseName: <删除 客户集团信息>
[2021-09-17 13:58:47,829] - logger.py] - INFO: 断言结果：pass (0 == 0)
[2021-09-17 13:58:47,832] - logger.py] - INFO: caseName: <禁用-启用 客户集团信息>
[2021-09-17 13:58:48,236] - logger.py] - INFO: 断言结果：pass (0 == 0)
[2021-09-17 13:58:48,238] - logger.py] - INFO: --------接口自动化测试结束------------
[2021-09-17 14:00:39,194] - logger.py] - INFO: --------接口自动化测试开始------------
[2021-09-17 14:00:39,195] - logger.py] - INFO: caseName: <新增集团（启用状态）>
[2021-09-17 14:00:40,029] - logger.py] - INFO: 断言结果：pass (0 == 0)
[2021-09-17 14:00:40,086] - logger.py] - INFO: caseName: <客户集团基础信息编辑>
[2021-09-17 14:00:40,944] - logger.py] - INFO: 断言结果：pass (0 == 0)
[2021-09-17 14:00:40,948] - logger.py] - INFO: caseName: <禁用-启用 客户集团信息>
[2021-09-17 14:00:42,051] - logger.py] - INFO: caseName: <删除 客户集团信息>
[2021-09-17 14:00:42,511] - logger.py] - INFO: caseName: <禁用-启用 客户集团信息>
[2021-09-17 14:00:43,246] - logger.py] - INFO: --------接口自动化测试结束------------
[2021-09-17 14:02:14,322] - logger.py] - INFO: --------接口自动化测试开始------------
[2021-09-17 14:02:14,323] - logger.py] - INFO: caseName: <新增集团（启用状态）>
[2021-09-17 14:02:15,029] - logger.py] - INFO: 断言结果：pass (0 == 0)
[2021-09-17 14:02:15,211] - logger.py] - INFO: caseName: <客户集团基础信息编辑>
[2021-09-17 14:02:15,811] - logger.py] - INFO: 断言结果：pass (0 == 0)
[2021-09-17 14:02:15,817] - logger.py] - INFO: caseName: <禁用-启用 客户集团信息>
[2021-09-17 14:02:16,675] - logger.py] - INFO: caseName: <删除 客户集团信息>
[2021-09-17 14:02:17,169] - logger.py] - INFO: caseName: <禁用-启用 客户集团信息>
[2021-09-17 14:02:17,519] - logger.py] - INFO: --------接口自动化测试结束------------
[2021-09-17 14:04:05,890] - logger.py] - INFO: --------接口自动化测试开始------------
[2021-09-17 14:04:05,894] - logger.py] - INFO: caseName: <新增集团（启用状态）>
[2021-09-17 14:04:06,493] - logger.py] - INFO: 断言结果：pass (0 == 0)
[2021-09-17 14:05:50,151] - logger.py] - INFO: --------接口自动化测试结束------------
[2021-09-17 14:07:45,535] - logger.py] - INFO: --------接口自动化测试开始------------
[2021-09-17 14:07:45,538] - logger.py] - INFO: caseName: <新增集团（启用状态）>
[2021-09-17 14:07:45,778] - logger.py] - INFO: caseName: <客户集团基础信息编辑>
[2021-09-17 14:07:46,201] - logger.py] - INFO: 断言结果：pass (0 == 0)
[2021-09-17 14:07:59,982] - logger.py] - INFO: --------接口自动化测试结束------------
[2021-09-17 14:08:05,959] - logger.py] - INFO: --------接口自动化测试开始------------
[2021-09-17 14:08:05,962] - logger.py] - INFO: caseName: <新增集团（启用状态）>
[2021-09-17 14:08:06,211] - logger.py] - INFO: caseName: <客户集团基础信息编辑>
[2021-09-17 14:08:06,650] - logger.py] - INFO: 断言结果：pass (0 == 0)
[2021-09-17 14:08:13,878] - logger.py] - INFO: --------接口自动化测试结束------------
[2021-09-17 14:08:45,015] - logger.py] - INFO: --------接口自动化测试开始------------
[2021-09-17 14:08:45,016] - logger.py] - INFO: caseName: <新增集团（启用状态）>
[2021-09-17 14:08:45,189] - logger.py] - INFO: caseName: <客户集团基础信息编辑>
[2021-09-17 14:08:45,574] - logger.py] - INFO: 断言结果：pass (0 == 0)
[2021-09-17 14:08:45,577] - logger.py] - INFO: caseName: <禁用-启用 客户集团信息>
[2021-09-17 14:08:45,811] - logger.py] - INFO: --------接口自动化测试结束------------
[2021-09-17 14:09:57,571] - logger.py] - INFO: --------接口自动化测试开始------------
[2021-09-17 14:09:57,574] - logger.py] - INFO: caseName: <新增集团（启用状态）>
[2021-09-17 14:09:58,443] - logger.py] - INFO: 断言结果：pass (0 == 0)
[2021-09-17 14:12:10,283] - logger.py] - INFO: --------接口自动化测试结束------------
[2021-09-17 14:12:11,761] - logger.py] - INFO: --------接口自动化测试开始------------
[2021-09-17 14:12:11,765] - logger.py] - INFO: caseName: <新增集团（启用状态）>
[2021-09-17 14:12:12,191] - logger.py] - INFO: caseName: <客户集团基础信息编辑>
[2021-09-17 14:12:12,898] - logger.py] - INFO: 断言结果：pass (0 == 0)
[2021-09-17 14:13:11,747] - logger.py] - INFO: --------接口自动化测试结束------------
[2021-09-17 14:13:13,287] - logger.py] - INFO: --------接口自动化测试开始------------
[2021-09-17 14:13:13,290] - logger.py] - INFO: caseName: <新增集团（启用状态）>
[2021-09-17 14:13:13,709] - logger.py] - INFO: caseName: <客户集团基础信息编辑>
[2021-09-17 14:13:14,326] - logger.py] - INFO: 断言结果：pass (0 == 0)
[2021-09-17 14:13:26,730] - logger.py] - INFO: --------接口自动化测试结束------------
[2021-09-17 14:13:28,301] - logger.py] - INFO: --------接口自动化测试开始------------
[2021-09-17 14:13:28,304] - logger.py] - INFO: caseName: <新增集团（启用状态）>
[2021-09-17 14:13:28,554] - logger.py] - INFO: caseName: <客户集团基础信息编辑>
[2021-09-17 14:13:28,984] - logger.py] - INFO: 断言结果：pass (0 == 0)
[2021-09-17 14:14:05,628] - logger.py] - INFO: --------接口自动化测试结束------------
[2021-09-17 14:14:07,099] - logger.py] - INFO: --------接口自动化测试开始------------
[2021-09-17 14:14:07,103] - logger.py] - INFO: caseName: <新增集团（启用状态）>
[2021-09-17 14:14:07,726] - logger.py] - INFO: caseName: <客户集团基础信息编辑>
[2021-09-17 14:14:08,083] - logger.py] - INFO: 断言结果：pass (0 == 0)
[2021-09-17 14:14:37,695] - logger.py] - INFO: --------接口自动化测试结束------------
[2021-09-17 14:14:41,887] - logger.py] - INFO: --------接口自动化测试开始------------
[2021-09-17 14:14:41,890] - logger.py] - INFO: caseName: <新增集团（启用状态）>
[2021-09-17 14:14:43,407] - logger.py] - INFO: caseName: <客户集团基础信息编辑>
[2021-09-17 14:14:44,139] - logger.py] - INFO: 断言结果：pass (0 == 0)
[2021-09-17 14:14:49,964] - logger.py] - INFO: --------接口自动化测试结束------------
[2021-09-17 14:14:51,384] - logger.py] - INFO: --------接口自动化测试开始------------
[2021-09-17 14:14:51,387] - logger.py] - INFO: caseName: <新增集团（启用状态）>
[2021-09-17 14:14:52,048] - logger.py] - INFO: caseName: <客户集团基础信息编辑>
[2021-09-17 14:14:52,616] - logger.py] - INFO: 断言结果：pass (0 == 0)
[2021-09-17 14:14:56,892] - logger.py] - INFO: --------接口自动化测试结束------------
[2021-09-17 14:15:34,641] - logger.py] - INFO: --------接口自动化测试开始------------
[2021-09-17 14:15:34,644] - logger.py] - INFO: caseName: <新增集团（启用状态）>
[2021-09-17 14:15:35,580] - logger.py] - INFO: caseName: <客户集团基础信息编辑>
[2021-09-17 14:15:36,207] - logger.py] - INFO: 断言结果：pass (0 == 0)
[2021-09-17 14:16:26,124] - logger.py] - INFO: --------接口自动化测试结束------------
[2021-09-17 14:16:30,771] - logger.py] - INFO: --------接口自动化测试开始------------
[2021-09-17 14:16:30,772] - logger.py] - INFO: caseName: <新增集团（启用状态）>
[2021-09-17 14:16:31,149] - logger.py] - INFO: caseName: <客户集团基础信息编辑>
[2021-09-17 14:16:31,645] - logger.py] - INFO: 断言结果：pass (0 == 0)
[2021-09-17 14:16:31,647] - logger.py] - INFO: caseName: <禁用-启用 客户集团信息>
[2021-09-17 14:16:31,973] - logger.py] - INFO: --------接口自动化测试结束------------
[2021-09-17 14:18:03,700] - logger.py] - INFO: --------接口自动化测试开始------------
[2021-09-17 14:18:03,705] - logger.py] - INFO: caseName: <新增集团（启用状态）>
[2021-09-17 14:18:04,000] - logger.py] - INFO: caseName: <客户集团基础信息编辑>
[2021-09-17 14:18:04,570] - logger.py] - INFO: 断言结果：pass (0 == 0)
[2021-09-17 14:20:40,167] - logger.py] - INFO: --------接口自动化测试结束------------
[2021-09-17 14:21:12,815] - logger.py] - INFO: --------接口自动化测试开始------------
[2021-09-17 14:21:12,821] - logger.py] - INFO: caseName: <新增集团（启用状态）>
[2021-09-17 14:21:13,143] - logger.py] - INFO: caseName: <客户集团基础信息编辑>
[2021-09-17 14:21:13,753] - logger.py] - INFO: 断言结果：pass (0 == 0)
[2021-09-17 14:21:37,026] - logger.py] - INFO: caseName: <禁用-启用 客户集团信息>
[2021-09-17 14:21:37,367] - logger.py] - INFO: --------接口自动化测试结束------------
[2021-09-17 14:21:53,380] - logger.py] - INFO: --------接口自动化测试开始------------
[2021-09-17 14:21:53,384] - logger.py] - INFO: caseName: <新增集团（启用状态）>
[2021-09-17 14:21:53,714] - logger.py] - INFO: caseName: <客户集团基础信息编辑>
[2021-09-17 14:21:55,414] - logger.py] - INFO: 断言结果：pass (0 == 0)
[2021-09-17 14:24:10,761] - logger.py] - INFO: --------接口自动化测试结束------------
[2021-09-17 14:24:12,594] - logger.py] - INFO: --------接口自动化测试开始------------
[2021-09-17 14:24:12,594] - logger.py] - INFO: caseName: <新增集团（启用状态）>
[2021-09-17 14:24:12,904] - logger.py] - INFO: caseName: <客户集团基础信息编辑>
[2021-09-17 14:24:14,719] - logger.py] - INFO: 断言结果：pass (0 == 0)
[2021-09-17 14:24:14,722] - logger.py] - INFO: caseName: <禁用-启用 客户集团信息>
[2021-09-17 14:24:15,050] - logger.py] - INFO: --------接口自动化测试结束------------
[2021-09-17 14:24:59,131] - logger.py] - INFO: --------接口自动化测试开始------------
[2021-09-17 14:24:59,131] - logger.py] - INFO: caseName: <新增集团（启用状态）>
[2021-09-17 14:24:59,398] - logger.py] - INFO: caseName: <禁用-启用 客户集团信息>
[2021-09-17 14:24:59,682] - logger.py] - INFO: --------接口自动化测试结束------------
[2021-09-17 14:25:28,278] - logger.py] - INFO: --------接口自动化测试开始------------
[2021-09-17 14:25:28,280] - logger.py] - INFO: caseName: <新增集团（启用状态）>
[2021-09-17 14:25:28,936] - logger.py] - INFO: 断言结果：pass (0 == 0)
[2021-09-17 14:25:28,999] - logger.py] - INFO: caseName: <禁用-启用 客户集团信息>
[2021-09-17 14:25:29,372] - logger.py] - INFO: 断言结果：pass (0 == 0)
[2021-09-17 14:25:29,374] - logger.py] - INFO: --------接口自动化测试结束------------
[2021-09-17 14:27:19,286] - logger.py] - INFO: --------接口自动化测试开始------------
[2021-09-17 14:27:19,286] - logger.py] - INFO: caseName: <新增集团（启用状态）>
[2021-09-17 14:27:19,969] - logger.py] - INFO: 断言结果：pass (0 == 0)
[2021-09-17 14:27:20,027] - logger.py] - INFO: caseName: <禁用-启用 客户集团信息>
[2021-09-17 14:27:20,439] - logger.py] - INFO: 断言结果：pass (0 == 0)
[2021-09-17 14:27:20,442] - logger.py] - INFO: --------接口自动化测试结束------------
[2021-09-17 14:29:52,466] - logger.py] - INFO: --------接口自动化测试开始------------
[2021-09-17 14:29:52,467] - logger.py] - INFO: caseName: <新增集团（启用状态）>
[2021-09-17 14:29:53,086] - logger.py] - INFO: caseName: <禁用-启用 客户集团信息>
[2021-09-17 14:29:53,652] - logger.py] - INFO: 断言结果：pass (0 == 0)
[2021-09-17 14:29:53,654] - logger.py] - INFO: --------接口自动化测试结束------------
[2021-09-17 14:34:03,422] - logger.py] - INFO: --------接口自动化测试开始------------
[2021-09-17 14:34:03,423] - logger.py] - INFO: caseName: <新增集团（启用状态）>
[2021-09-17 14:34:04,213] - logger.py] - INFO: 断言结果：pass (0 == 0)
[2021-09-17 14:34:04,293] - logger.py] - INFO: caseName: <客户集团详细信息>
[2021-09-17 14:34:05,472] - logger.py] - INFO: 断言结果：pass (0 == 0)
[2021-09-17 14:34:05,479] - logger.py] - INFO: caseName: <禁用-启用 客户集团信息>
[2021-09-17 14:34:06,109] - logger.py] - INFO: --------接口自动化测试结束------------
[2021-09-17 14:35:12,956] - logger.py] - INFO: --------接口自动化测试开始------------
[2021-09-17 14:35:12,957] - logger.py] - INFO: caseName: <新增集团（启用状态）>
[2021-09-17 14:35:13,631] - logger.py] - INFO: 断言结果：pass (0 == 0)
[2021-09-17 14:35:13,713] - logger.py] - INFO: caseName: <客户集团详细信息>
[2021-09-17 14:35:14,963] - logger.py] - INFO: 断言结果：pass (0 == 0)
[2021-09-17 14:35:14,972] - logger.py] - INFO: caseName: <禁用-启用 客户集团信息>
[2021-09-17 14:35:15,653] - logger.py] - INFO: --------接口自动化测试结束------------
[2021-09-17 14:48:37,623] - logger.py] - INFO: --------接口自动化测试开始------------
[2021-09-17 14:48:37,624] - logger.py] - INFO: caseName: <新增集团（启用状态）>
[2021-09-17 14:48:38,305] - logger.py] - INFO: 断言结果：pass (0 == 0)
[2021-09-17 14:48:38,369] - logger.py] - INFO: caseName: <禁用-启用 客户集团信息>
[2021-09-17 14:48:38,803] - logger.py] - INFO: --------接口自动化测试结束------------
[2021-09-17 14:50:06,142] - logger.py] - INFO: --------接口自动化测试开始------------
[2021-09-17 14:50:06,143] - logger.py] - INFO: caseName: <新增集团（启用状态）>
[2021-09-17 14:50:06,289] - logger.py] - WARNING: 断言失败，请查看用例内断言数据
[2021-09-17 14:50:06,350] - logger.py] - INFO: caseName: <禁用-启用 客户集团信息>
[2021-09-17 14:50:06,420] - logger.py] - WARNING: 断言失败，请查看用例内断言数据
[2021-09-17 14:50:06,421] - logger.py] - INFO: --------接口自动化测试结束------------
[2021-09-17 14:50:40,102] - logger.py] - INFO: --------接口自动化测试开始------------
[2021-09-17 14:50:40,103] - logger.py] - INFO: caseName: <新增集团（启用状态）>
[2021-09-17 14:50:40,237] - logger.py] - WARNING: 断言失败，请查看用例内断言数据
[2021-09-17 14:50:40,305] - logger.py] - INFO: caseName: <禁用-启用 客户集团信息>
[2021-09-17 14:50:40,383] - logger.py] - WARNING: 断言失败，请查看用例内断言数据
[2021-09-17 14:50:40,384] - logger.py] - INFO: --------接口自动化测试结束------------
[2021-09-17 14:51:10,326] - logger.py] - INFO: --------接口自动化测试开始------------
[2021-09-17 14:51:10,326] - logger.py] - INFO: caseName: <新增集团（启用状态）>
[2021-09-17 14:51:10,521] - logger.py] - WARNING: 断言失败，请查看用例内断言数据
[2021-09-17 14:51:10,579] - logger.py] - INFO: caseName: <禁用-启用 客户集团信息>
[2021-09-17 14:51:10,622] - logger.py] - INFO: --------接口自动化测试结束------------
[2021-09-17 14:52:01,751] - logger.py] - INFO: --------接口自动化测试开始------------
[2021-09-17 14:52:01,752] - logger.py] - INFO: caseName: <新增集团（启用状态）>
[2021-09-17 14:52:01,911] - logger.py] - WARNING: 断言失败，请查看用例内断言数据
[2021-09-17 14:52:01,972] - logger.py] - INFO: caseName: <禁用-启用 客户集团信息>
[2021-09-17 14:52:02,028] - logger.py] - INFO: --------接口自动化测试结束------------
[2021-09-17 15:18:01,231] - logger.py] - INFO: --------接口自动化测试开始------------
[2021-09-17 15:18:01,232] - logger.py] - INFO: caseName: <新增集团（启用状态）>
[2021-09-17 15:18:01,426] - logger.py] - WARNING: 断言失败，请查看用例内断言数据
[2021-09-17 15:18:01,497] - logger.py] - INFO: caseName: <客户集团详细信息>
[2021-09-17 15:18:01,521] - logger.py] - INFO: caseName: <禁用-启用 客户集团信息>
[2021-09-17 15:18:01,526] - logger.py] - INFO: --------接口自动化测试结束------------
[2021-09-17 15:19:11,159] - logger.py] - INFO: --------接口自动化测试开始------------
[2021-09-17 15:19:11,159] - logger.py] - INFO: caseName: <新增集团（启用状态）>
[2021-09-17 15:19:11,331] - logger.py] - WARNING: 断言失败，请查看用例内断言数据
[2021-09-17 15:19:11,395] - logger.py] - INFO: caseName: <客户集团详细信息>
[2021-09-17 15:19:11,449] - logger.py] - INFO: caseName: <禁用-启用 客户集团信息>
[2021-09-17 15:19:11,455] - logger.py] - INFO: --------接口自动化测试结束------------
[2021-09-17 15:20:21,728] - logger.py] - INFO: --------接口自动化测试开始------------
[2021-09-17 15:20:21,729] - logger.py] - INFO: caseName: <新增集团（启用状态）>
[2021-09-17 15:20:22,202] - logger.py] - INFO: 断言结果：pass (0 == 0)
[2021-09-17 15:20:22,272] - logger.py] - INFO: caseName: <客户集团详细信息>
[2021-09-17 15:20:22,354] - logger.py] - INFO: caseName: <禁用-启用 客户集团信息>
[2021-09-17 15:20:22,365] - logger.py] - INFO: --------接口自动化测试结束------------
[2021-09-17 15:21:14,722] - logger.py] - INFO: --------接口自动化测试开始------------
[2021-09-17 15:21:14,723] - logger.py] - INFO: caseName: <新增集团（启用状态）>
[2021-09-17 15:21:14,864] - logger.py] - WARNING: 断言失败，请查看用例内断言数据
[2021-09-17 15:21:14,929] - logger.py] - INFO: caseName: <客户集团详细信息>
[2021-09-17 15:21:14,967] - logger.py] - INFO: caseName: <禁用-启用 客户集团信息>
[2021-09-17 15:21:14,974] - logger.py] - INFO: --------接口自动化测试结束------------
[2021-09-17 15:21:24,784] - logger.py] - INFO: --------接口自动化测试开始------------
[2021-09-17 15:21:24,784] - logger.py] - INFO: caseName: <新增集团（启用状态）>
[2021-09-17 15:21:25,017] - logger.py] - WARNING: 断言失败，请查看用例内断言数据
[2021-09-17 15:21:25,076] - logger.py] - INFO: caseName: <客户集团详细信息>
[2021-09-17 15:21:26,075] - logger.py] - INFO: 断言结果：pass (0 == 0)
[2021-09-17 15:21:26,084] - logger.py] - INFO: caseName: <禁用-启用 客户集团信息>
[2021-09-17 15:21:26,575] - logger.py] - INFO: 断言结果：pass (0 == 0)
[2021-09-17 15:21:26,578] - logger.py] - INFO: --------接口自动化测试结束------------
[2021-09-17 15:24:08,972] - logger.py] - INFO: --------接口自动化测试开始------------
[2021-09-17 15:24:08,973] - logger.py] - INFO: caseName: <新增集团（启用状态）>
[2021-09-17 15:24:09,204] - logger.py] - WARNING: 断言失败，请查看用例内断言数据
[2021-09-17 15:24:09,259] - logger.py] - INFO: caseName: <客户集团详细信息>
[2021-09-17 15:24:10,413] - logger.py] - INFO: 断言结果：pass (0 == 0)
[2021-09-17 15:24:10,424] - logger.py] - INFO: caseName: <禁用-启用 客户集团信息>
[2021-09-17 15:24:11,255] - logger.py] - INFO: 断言结果：pass (0 == 0)
[2021-09-17 15:24:11,258] - logger.py] - INFO: --------接口自动化测试结束------------
[2021-09-17 15:28:40,122] - logger.py] - INFO: --------接口自动化测试开始------------
[2021-09-17 15:28:40,123] - logger.py] - INFO: caseName: <新增集团（启用状态）>
[2021-09-17 15:28:40,287] - logger.py] - WARNING: 断言失败，请查看用例内断言数据
[2021-09-17 15:28:40,350] - logger.py] - INFO: caseName: <客户集团详细信息>
[2021-09-17 15:28:41,113] - logger.py] - INFO: 断言结果：pass (0 == 0)
[2021-09-17 15:28:41,121] - logger.py] - INFO: caseName: <禁用-启用 客户集团信息>
[2021-09-17 15:28:41,490] - logger.py] - INFO: 断言结果：pass (0 == 0)
[2021-09-17 15:28:41,492] - logger.py] - INFO: --------接口自动化测试结束------------
[2021-09-17 15:29:04,089] - logger.py] - INFO: --------接口自动化测试开始------------
[2021-09-17 15:29:04,090] - logger.py] - INFO: caseName: <新增集团（启用状态）>
[2021-09-17 15:29:04,232] - logger.py] - WARNING: 断言失败，请查看用例内断言数据
[2021-09-17 15:29:04,306] - logger.py] - INFO: caseName: <客户集团详细信息>
[2021-09-17 15:29:04,942] - logger.py] - INFO: 断言结果：pass (0 == 0)
[2021-09-17 15:29:04,948] - logger.py] - INFO: caseName: <禁用-启用 客户集团信息>
[2021-09-17 15:29:05,275] - logger.py] - INFO: 断言结果：pass (0 == 0)
[2021-09-17 15:29:05,277] - logger.py] - INFO: --------接口自动化测试结束------------
[2021-09-17 15:29:16,173] - logger.py] - INFO: --------接口自动化测试开始------------
[2021-09-17 15:29:16,173] - logger.py] - INFO: caseName: <新增集团（启用状态）>
[2021-09-17 15:29:16,302] - logger.py] - WARNING: 断言失败，请查看用例内断言数据
[2021-09-17 15:29:16,375] - logger.py] - INFO: caseName: <客户集团详细信息>
[2021-09-17 15:29:17,060] - logger.py] - INFO: 断言结果：pass (0 == 0)
[2021-09-17 15:29:17,070] - logger.py] - INFO: caseName: <禁用-启用 客户集团信息>
[2021-09-17 15:29:17,717] - logger.py] - INFO: 断言结果：pass (0 == 0)
[2021-09-17 15:29:17,720] - logger.py] - INFO: --------接口自动化测试结束------------
[2021-09-17 15:29:38,755] - logger.py] - INFO: --------接口自动化测试开始------------
[2021-09-17 15:29:38,756] - logger.py] - INFO: caseName: <新增集团（启用状态）>
[2021-09-17 15:29:38,893] - logger.py] - WARNING: 断言失败，请查看用例内断言数据
[2021-09-17 15:29:38,973] - logger.py] - INFO: caseName: <客户集团详细信息>
[2021-09-17 15:29:39,637] - logger.py] - INFO: 断言结果：pass (0 == 0)
[2021-09-17 15:29:39,647] - logger.py] - INFO: caseName: <禁用-启用 客户集团信息>
[2021-09-17 15:29:39,978] - logger.py] - INFO: 断言结果：pass (0 == 0)
[2021-09-17 15:29:39,979] - logger.py] - INFO: --------接口自动化测试结束------------
[2021-09-17 15:30:05,684] - logger.py] - INFO: --------接口自动化测试开始------------
[2021-09-17 15:30:05,684] - logger.py] - INFO: caseName: <新增集团（启用状态）>
[2021-09-17 15:30:05,825] - logger.py] - WARNING: 断言失败，请查看用例内断言数据
[2021-09-17 15:30:05,875] - logger.py] - INFO: caseName: <客户集团详细信息>
[2021-09-17 15:30:06,563] - logger.py] - INFO: 断言结果：pass (0 == 0)
[2021-09-17 15:30:06,578] - logger.py] - INFO: caseName: <禁用-启用 客户集团信息>
[2021-09-17 15:30:06,921] - logger.py] - INFO: 断言结果：pass (0 == 0)
[2021-09-17 15:30:06,922] - logger.py] - INFO: --------接口自动化测试结束------------
[2021-09-17 15:33:25,002] - logger.py] - INFO: --------接口自动化测试开始------------
[2021-09-17 15:33:25,002] - logger.py] - INFO: caseName: <新增集团（启用状态）>
[2021-09-17 15:33:25,159] - logger.py] - WARNING: 断言失败，请查看用例内断言数据
[2021-09-17 15:33:25,212] - logger.py] - INFO: caseName: <客户集团详细信息>
[2021-09-17 15:33:25,984] - logger.py] - INFO: 断言结果：pass (0 == 0)
[2021-09-17 15:33:25,998] - logger.py] - INFO: caseName: <禁用-启用 客户集团信息>
[2021-09-17 15:33:26,286] - logger.py] - INFO: 断言结果：pass (0 == 0)
[2021-09-17 15:33:26,287] - logger.py] - INFO: --------接口自动化测试结束------------
[2021-09-17 15:35:32,534] - logger.py] - INFO: --------接口自动化测试开始------------
[2021-09-17 15:35:32,534] - logger.py] - INFO: caseName: <新增集团（启用状态）>
[2021-09-17 15:35:32,668] - logger.py] - WARNING: 断言失败，请查看用例内断言数据
[2021-09-17 15:35:32,724] - logger.py] - INFO: caseName: <客户集团详细信息>
[2021-09-17 15:35:32,833] - logger.py] - WARNING: 断言失败，请查看用例内断言数据
[2021-09-17 15:35:32,836] - logger.py] - INFO: caseName: <禁用-启用 客户集团信息>
[2021-09-17 15:35:33,109] - logger.py] - INFO: 断言结果：pass (0 == 0)
[2021-09-17 15:35:33,110] - logger.py] - INFO: --------接口自动化测试结束------------
[2021-09-17 15:36:08,636] - logger.py] - INFO: --------接口自动化测试开始------------
[2021-09-17 15:36:08,637] - logger.py] - INFO: caseName: <新增集团（启用状态）>
[2021-09-17 15:36:08,771] - logger.py] - WARNING: 断言失败，请查看用例内断言数据
[2021-09-17 15:36:08,829] - logger.py] - INFO: caseName: <客户集团详细信息>
[2021-09-17 15:36:08,919] - logger.py] - WARNING: 断言失败，请查看用例内断言数据
[2021-09-17 15:36:08,927] - logger.py] - INFO: caseName: <禁用-启用 客户集团信息>
[2021-09-17 15:36:09,227] - logger.py] - INFO: 断言结果：pass (0 == 0)
[2021-09-17 15:36:09,229] - logger.py] - INFO: --------接口自动化测试结束------------
[2021-09-17 15:37:16,236] - logger.py] - INFO: --------接口自动化测试开始------------
[2021-09-17 15:37:16,237] - logger.py] - INFO: caseName: <新增集团（启用状态）>
[2021-09-17 15:37:16,508] - logger.py] - WARNING: 断言失败，请查看用例内断言数据
[2021-09-17 15:37:16,575] - logger.py] - INFO: caseName: <客户集团详细信息>
[2021-09-17 15:37:16,667] - logger.py] - WARNING: 断言失败，请查看用例内断言数据
[2021-09-17 15:37:16,675] - logger.py] - INFO: caseName: <禁用-启用 客户集团信息>
[2021-09-17 15:37:17,362] - logger.py] - INFO: 断言结果：pass (0 == 0)
[2021-09-17 15:37:17,363] - logger.py] - INFO: --------接口自动化测试结束------------
[2021-09-17 15:37:31,207] - logger.py] - INFO: --------接口自动化测试开始------------
[2021-09-17 15:37:31,208] - logger.py] - INFO: caseName: <新增集团（启用状态）>
[2021-09-17 15:37:31,419] - logger.py] - WARNING: 断言失败，请查看用例内断言数据
[2021-09-17 15:37:31,488] - logger.py] - INFO: caseName: <客户集团详细信息>
[2021-09-17 15:37:31,579] - logger.py] - WARNING: 断言失败，请查看用例内断言数据
[2021-09-17 15:37:31,581] - logger.py] - INFO: caseName: <禁用-启用 客户集团信息>
[2021-09-17 15:37:31,957] - logger.py] - INFO: 断言结果：pass (0 == 0)
[2021-09-17 15:37:31,959] - logger.py] - INFO: --------接口自动化测试结束------------
[2021-09-17 16:41:03,905] - logger.py] - INFO: --------接口自动化测试开始------------
[2021-09-17 16:41:03,906] - logger.py] - INFO: caseName: <新增集团（启用状态）>
[2021-09-17 16:41:03,939] - logger.py] - INFO: caseName: <客户集团详细信息>
[2021-09-17 16:41:04,448] - logger.py] - WARNING: 断言失败，请查看用例内断言数据
[2021-09-17 16:41:04,450] - logger.py] - INFO: caseName: <禁用-启用 客户集团信息>
[2021-09-17 16:41:04,456] - logger.py] - INFO: --------接口自动化测试结束------------
[2021-09-17 16:41:34,259] - logger.py] - INFO: --------接口自动化测试开始------------
[2021-09-17 16:41:34,260] - logger.py] - INFO: caseName: <新增集团（启用状态）>
[2021-09-17 16:41:34,285] - logger.py] - INFO: caseName: <客户集团详细信息>
[2021-09-17 16:41:34,467] - logger.py] - INFO: 断言结果：pass (0 == 0)
[2021-09-17 16:41:34,469] - logger.py] - INFO: caseName: <禁用-启用 客户集团信息>
[2021-09-17 16:41:34,475] - logger.py] - INFO: --------接口自动化测试结束------------
[2021-09-17 16:42:29,534] - logger.py] - INFO: --------接口自动化测试开始------------
[2021-09-17 16:42:29,535] - logger.py] - INFO: caseName: <新增集团（启用状态）>
[2021-09-17 16:42:29,616] - logger.py] - WARNING: 断言失败，请查看用例内断言数据
[2021-09-17 16:42:29,673] - logger.py] - INFO: caseName: <客户集团详细信息>
[2021-09-17 16:42:29,830] - logger.py] - INFO: 断言结果：pass (0 == 0)
[2021-09-17 16:42:29,838] - logger.py] - INFO: caseName: <禁用-启用 客户集团信息>
[2021-09-17 16:42:30,024] - logger.py] - WARNING: 断言失败，请查看用例内断言数据
[2021-09-17 16:42:30,024] - logger.py] - INFO: --------接口自动化测试结束------------
[2021-09-17 16:43:38,598] - logger.py] - INFO: --------接口自动化测试开始------------
[2021-09-17 16:43:38,599] - logger.py] - INFO: caseName: <新增集团（启用状态）>
[2021-09-17 16:43:38,677] - logger.py] - WARNING: 断言失败，请查看用例内断言数据
[2021-09-17 16:43:38,736] - logger.py] - INFO: caseName: <客户集团详细信息>
[2021-09-17 16:43:38,899] - logger.py] - INFO: 断言结果：pass (0 == 0)
[2021-09-17 16:43:38,900] - logger.py] - INFO: caseName: <禁用-启用 客户集团信息>
[2021-09-17 16:43:39,051] - logger.py] - WARNING: 断言失败，请查看用例内断言数据
[2021-09-17 16:43:39,053] - logger.py] - INFO: --------接口自动化测试结束------------
[2021-09-17 16:44:19,797] - logger.py] - INFO: --------接口自动化测试开始------------
[2021-09-17 16:44:19,798] - logger.py] - INFO: caseName: <新增集团（启用状态）>
[2021-09-17 16:44:20,041] - logger.py] - WARNING: 断言失败，请查看用例内断言数据
[2021-09-17 16:44:20,558] - logger.py] - INFO: caseName: <客户集团详细信息>
[2021-09-17 16:44:21,556] - logger.py] - INFO: 断言结果：pass (0 == 0)
[2021-09-17 16:44:21,565] - logger.py] - INFO: caseName: <禁用-启用 客户集团信息>
[2021-09-17 16:44:22,571] - logger.py] - WARNING: 断言失败，请查看用例内断言数据
[2021-09-17 16:44:22,573] - logger.py] - INFO: --------接口自动化测试结束------------
[2021-09-17 16:44:51,439] - logger.py] - INFO: --------接口自动化测试开始------------
[2021-09-17 16:44:51,440] - logger.py] - INFO: caseName: <新增集团（启用状态）>
[2021-09-17 16:44:52,061] - logger.py] - WARNING: 断言失败，请查看用例内断言数据
[2021-09-17 16:44:52,642] - logger.py] - INFO: caseName: <客户集团详细信息>
[2021-09-17 16:44:53,420] - logger.py] - WARNING: 断言失败，请查看用例内断言数据
[2021-09-17 16:44:53,428] - logger.py] - INFO: caseName: <禁用-启用 客户集团信息>
[2021-09-17 16:44:53,808] - logger.py] - WARNING: 断言失败，请查看用例内断言数据
[2021-09-17 16:44:53,811] - logger.py] - INFO: --------接口自动化测试结束------------
[2021-09-17 16:45:36,677] - logger.py] - INFO: --------接口自动化测试开始------------
[2021-09-17 16:45:36,677] - logger.py] - INFO: caseName: <新增集团（启用状态）>
[2021-09-17 16:45:36,751] - logger.py] - WARNING: 断言失败，请查看用例内断言数据
[2021-09-17 16:45:36,862] - logger.py] - INFO: caseName: <客户集团详细信息>
[2021-09-17 16:45:37,721] - logger.py] - WARNING: 断言失败，请查看用例内断言数据
[2021-09-17 16:45:37,728] - logger.py] - INFO: caseName: <禁用-启用 客户集团信息>
[2021-09-17 16:45:37,894] - logger.py] - WARNING: 断言失败，请查看用例内断言数据
[2021-09-17 16:45:37,896] - logger.py] - INFO: --------接口自动化测试结束------------
[2021-09-17 16:46:17,095] - logger.py] - INFO: --------接口自动化测试开始------------
[2021-09-17 16:46:17,095] - logger.py] - INFO: caseName: <新增集团（启用状态）>
[2021-09-17 16:46:17,161] - logger.py] - WARNING: 断言失败，请查看用例内断言数据
[2021-09-17 16:46:17,222] - logger.py] - ERROR: {"code":1,"msg":"Required request body is missing: public com.mkh.st.common.core.util.R<java.lang.Boolean> com.mkh.st.order.controller.GroupController.addGroup(com.mkh.st.order.dto.GroupAddDTO)","data":null}
[2021-09-17 16:46:17,225] - logger.py] - INFO: caseName: <客户集团详细信息>
[2021-09-17 16:46:17,373] - logger.py] - ERROR: {"code":1,"msg":"无此客户！","data":1}
[2021-09-17 16:46:17,376] - logger.py] - INFO: caseName: <禁用-启用 客户集团信息>
[2021-09-17 16:46:17,516] - logger.py] - WARNING: 断言失败，请查看用例内断言数据
[2021-09-17 16:46:17,518] - logger.py] - INFO: --------接口自动化测试结束------------
[2021-09-17 16:49:06,165] - logger.py] - INFO: --------接口自动化测试开始------------
[2021-09-17 16:49:06,165] - logger.py] - INFO: caseName: <新增集团（启用状态）>
[2021-09-17 16:49:07,118] - logger.py] - ERROR: {"code":1,"msg":"Required request body is missing: public com.mkh.st.common.core.util.R<java.lang.Boolean> com.mkh.st.order.controller.GroupController.addGroup(com.mkh.st.order.dto.GroupAddDTO)","data":null}
[2021-09-17 16:49:07,123] - logger.py] - INFO: caseName: <客户集团详细信息>
[2021-09-17 16:49:07,991] - logger.py] - ERROR: {"code":1,"msg":"无此客户！","data":1}
[2021-09-17 16:49:07,996] - logger.py] - INFO: caseName: <禁用-启用 客户集团信息>
[2021-09-17 16:49:09,061] - logger.py] - ERROR: {"code":1,"msg":"Required request body is missing: public com.mkh.st.common.core.util.R<java.lang.Boolean> com.mkh.st.order.controller.GroupController.enableGroup(com.mkh.st.order.dto.CustomerEnableDTO)","data":null}
[2021-09-17 16:49:09,063] - logger.py] - INFO: --------接口自动化测试结束------------
[2021-09-17 16:49:42,959] - logger.py] - INFO: --------接口自动化测试开始------------
[2021-09-17 16:49:42,960] - logger.py] - INFO: caseName: <新增集团（启用状态）>
[2021-09-17 16:49:43,042] - logger.py] - ERROR: {"code":1,"msg":"Required request body is missing: public com.mkh.st.common.core.util.R<java.lang.Boolean> com.mkh.st.order.controller.GroupController.addGroup(com.mkh.st.order.dto.GroupAddDTO)","data":null}
[2021-09-17 16:49:43,048] - logger.py] - INFO: caseName: <客户集团详细信息>
[2021-09-17 16:49:43,151] - logger.py] - ERROR: {"code":1,"msg":"无此客户！","data":1}
[2021-09-17 16:49:43,155] - logger.py] - INFO: caseName: <禁用-启用 客户集团信息>
[2021-09-17 16:49:43,311] - logger.py] - ERROR: {"code":1,"msg":"Required request body is missing: public com.mkh.st.common.core.util.R<java.lang.Boolean> com.mkh.st.order.controller.GroupController.enableGroup(com.mkh.st.order.dto.CustomerEnableDTO)","data":null}
[2021-09-17 16:49:43,313] - logger.py] - INFO: --------接口自动化测试结束------------
[2021-09-17 16:50:34,115] - logger.py] - INFO: --------接口自动化测试开始------------
[2021-09-17 16:50:34,124] - logger.py] - INFO: caseName: <新增集团（启用状态）>
[2021-09-17 16:52:26,517] - logger.py] - INFO: --------接口自动化测试结束------------
[2021-09-17 16:53:20,058] - logger.py] - INFO: --------接口自动化测试开始------------
[2021-09-17 16:53:20,059] - logger.py] - INFO: caseName: <新增集团（启用状态）>
[2021-09-17 16:53:20,577] - logger.py] - ERROR: {"code":1,"msg":"Required request body is missing: public com.mkh.st.common.core.util.R<java.lang.Boolean> com.mkh.st.order.controller.GroupController.addGroup(com.mkh.st.order.dto.GroupAddDTO)","data":null}
[2021-09-17 16:53:20,582] - logger.py] - INFO: caseName: <客户集团详细信息>
[2021-09-17 16:53:20,793] - logger.py] - ERROR: {"code":1,"msg":"无此客户！","data":1}
[2021-09-17 16:53:20,798] - logger.py] - INFO: caseName: <禁用-启用 客户集团信息>
[2021-09-17 16:53:21,191] - logger.py] - ERROR: {"code":1,"msg":"Required request body is missing: public com.mkh.st.common.core.util.R<java.lang.Boolean> com.mkh.st.order.controller.GroupController.enableGroup(com.mkh.st.order.dto.CustomerEnableDTO)","data":null}
[2021-09-17 16:53:21,194] - logger.py] - INFO: --------接口自动化测试结束------------
[2021-09-17 16:54:59,555] - logger.py] - INFO: --------接口自动化测试开始------------
[2021-09-17 16:54:59,555] - logger.py] - INFO: caseName: <新增集团（启用状态）>
[2021-09-17 16:55:00,141] - logger.py] - ERROR: {"code":1,"msg":"Required request body is missing: public com.mkh.st.common.core.util.R<java.lang.Boolean> com.mkh.st.order.controller.GroupController.addGroup(com.mkh.st.order.dto.GroupAddDTO)","data":null}
[2021-09-17 16:55:00,147] - logger.py] - INFO: caseName: <客户集团详细信息>
[2021-09-17 16:55:00,761] - logger.py] - ERROR: {"code":1,"msg":"无此客户！","data":1}
[2021-09-17 16:55:00,766] - logger.py] - INFO: caseName: <禁用-启用 客户集团信息>
[2021-09-17 16:55:01,171] - logger.py] - ERROR: {"code":1,"msg":"Required request body is missing: public com.mkh.st.common.core.util.R<java.lang.Boolean> com.mkh.st.order.controller.GroupController.enableGroup(com.mkh.st.order.dto.CustomerEnableDTO)","data":null}
[2021-09-17 16:55:01,174] - logger.py] - INFO: --------接口自动化测试结束------------
[2021-09-17 16:57:50,221] - logger.py] - INFO: --------接口自动化测试开始------------
[2021-09-17 16:57:50,222] - logger.py] - INFO: caseName: <新增集团（启用状态）>
[2021-09-17 16:57:50,346] - logger.py] - ERROR: {"code":1,"msg":"Required request body is missing: public com.mkh.st.common.core.util.R<java.lang.Boolean> com.mkh.st.order.controller.GroupController.addGroup(com.mkh.st.order.dto.GroupAddDTO)","data":null}
[2021-09-17 16:57:50,348] - logger.py] - INFO: caseName: <客户集团详细信息>
[2021-09-17 16:57:50,449] - logger.py] - ERROR: {"code":1,"msg":"无此客户！","data":1}
[2021-09-17 16:57:50,453] - logger.py] - INFO: caseName: <禁用-启用 客户集团信息>
[2021-09-17 16:57:50,635] - logger.py] - ERROR: {"code":1,"msg":"Required request body is missing: public com.mkh.st.common.core.util.R<java.lang.Boolean> com.mkh.st.order.controller.GroupController.enableGroup(com.mkh.st.order.dto.CustomerEnableDTO)","data":null}
[2021-09-17 16:57:50,636] - logger.py] - INFO: --------接口自动化测试结束------------
[2021-09-17 17:01:00,418] - logger.py] - INFO: --------接口自动化测试开始------------
[2021-09-17 17:01:00,423] - logger.py] - INFO: caseName: <新增集团（启用状态）>
[2021-09-17 17:02:44,419] - logger.py] - INFO: --------接口自动化测试结束------------
[2021-09-17 17:03:15,897] - logger.py] - INFO: --------接口自动化测试开始------------
[2021-09-17 17:03:15,897] - logger.py] - INFO: caseName: <新增集团（启用状态）>
[2021-09-17 17:03:16,053] - logger.py] - ERROR: {"code":1,"msg":"手机号码已存在!","data":1}
[2021-09-17 17:03:16,055] - logger.py] - INFO: caseName: <客户集团详细信息>
[2021-09-17 17:03:16,056] - logger.py] - WARNING: 出现如下异常:'NoneType' object has no attribute 'text'
[2021-09-17 17:03:16,057] - logger.py] - INFO: caseName: <禁用-启用 客户集团信息>
[2021-09-17 17:03:16,857] - logger.py] - INFO: 断言结果：pass (0 == 0)
[2021-09-17 17:03:16,860] - logger.py] - INFO: --------接口自动化测试结束------------
[2021-09-17 17:04:29,231] - logger.py] - INFO: --------接口自动化测试开始------------
[2021-09-17 17:04:29,232] - logger.py] - INFO: caseName: <新增集团（启用状态）>
[2021-09-17 17:04:29,377] - logger.py] - ERROR: {"code":1,"msg":"手机号码已存在!","data":1}
[2021-09-17 17:04:29,379] - logger.py] - INFO: caseName: <客户集团详细信息>
[2021-09-17 17:04:29,470] - logger.py] - ERROR: {"code":1,"msg":"无此客户！","data":1}
[2021-09-17 17:04:29,476] - logger.py] - INFO: caseName: <禁用-启用 客户集团信息>
[2021-09-17 17:04:29,837] - logger.py] - INFO: 断言结果：pass (0 == 0)
[2021-09-17 17:04:29,838] - logger.py] - INFO: --------接口自动化测试结束------------
[2021-09-17 17:05:00,548] - logger.py] - INFO: --------接口自动化测试开始------------
[2021-09-17 17:05:00,549] - logger.py] - INFO: caseName: <新增集团（启用状态）>
[2021-09-17 17:05:01,103] - logger.py] - INFO: 断言结果：pass (0 == 0)
[2021-09-17 17:05:01,154] - logger.py] - INFO: caseName: <客户集团详细信息>
[2021-09-17 17:05:01,253] - logger.py] - ERROR: {"code":1,"msg":"无此客户！","data":1}
[2021-09-17 17:05:01,258] - logger.py] - INFO: caseName: <禁用-启用 客户集团信息>
[2021-09-17 17:05:01,615] - logger.py] - INFO: 断言结果：pass (0 == 0)
[2021-09-17 17:05:01,617] - logger.py] - INFO: --------接口自动化测试结束------------
[2021-09-17 17:06:06,539] - logger.py] - INFO: --------接口自动化测试开始------------
[2021-09-17 17:06:06,540] - logger.py] - INFO: caseName: <新增集团（启用状态）>
[2021-09-17 17:06:07,065] - logger.py] - INFO: 断言结果：pass (0 == 0)
[2021-09-17 17:06:07,124] - logger.py] - INFO: caseName: <客户集团详细信息>
[2021-09-17 17:06:07,224] - logger.py] - ERROR: {"code":1,"msg":"无此客户！","data":1}
[2021-09-17 17:06:07,229] - logger.py] - INFO: caseName: <删除 客户集团信息>
[2021-09-17 17:06:08,664] - logger.py] - INFO: 断言结果：pass (0 == 0)
[2021-09-17 17:06:08,669] - logger.py] - INFO: caseName: <禁用-启用 客户集团信息>
[2021-09-17 17:06:08,999] - logger.py] - INFO: 断言结果：pass (0 == 0)
[2021-09-17 17:06:09,001] - logger.py] - INFO: --------接口自动化测试结束------------
[2021-09-17 17:06:17,444] - logger.py] - INFO: --------接口自动化测试开始------------
[2021-09-17 17:06:17,445] - logger.py] - INFO: caseName: <新增集团（启用状态）>
[2021-09-17 17:06:17,624] - logger.py] - ERROR: {"code":1,"msg":"手机号码已存在!","data":1}
[2021-09-17 17:06:17,629] - logger.py] - INFO: caseName: <客户集团详细信息>
[2021-09-17 17:06:17,724] - logger.py] - ERROR: {"code":1,"msg":"无此客户！","data":1}
[2021-09-17 17:06:17,730] - logger.py] - INFO: caseName: <删除 客户集团信息>
[2021-09-17 17:06:18,155] - logger.py] - INFO: 断言结果：pass (0 == 0)
[2021-09-17 17:06:18,161] - logger.py] - INFO: caseName: <禁用-启用 客户集团信息>
[2021-09-17 17:06:18,527] - logger.py] - INFO: 断言结果：pass (0 == 0)
[2021-09-17 17:06:18,529] - logger.py] - INFO: --------接口自动化测试结束------------
[2021-09-17 17:09:30,174] - logger.py] - INFO: --------接口自动化测试开始------------
[2021-09-17 17:09:30,175] - logger.py] - INFO: caseName: <新增集团（启用状态）>
[2021-09-17 17:09:30,377] - logger.py] - ERROR: {"code":1,"msg":"手机号码已存在!","data":1}
[2021-09-17 17:09:30,382] - logger.py] - INFO: caseName: <客户集团详细信息>
[2021-09-17 17:09:30,389] - logger.py] - WARNING: 出现如下异常:'NoneType' object has no attribute 'text'
[2021-09-17 17:09:30,395] - logger.py] - INFO: caseName: <删除 客户集团信息>
[2021-09-17 17:09:30,946] - logger.py] - INFO: 断言结果：pass (0 == 0)
[2021-09-17 17:09:30,951] - logger.py] - INFO: caseName: <禁用-启用 客户集团信息>
[2021-09-17 17:09:31,397] - logger.py] - INFO: 断言结果：pass (0 == 0)
[2021-09-17 17:09:31,399] - logger.py] - INFO: --------接口自动化测试结束------------
[2021-09-17 17:09:54,108] - logger.py] - INFO: --------接口自动化测试开始------------
[2021-09-17 17:09:54,109] - logger.py] - INFO: caseName: <新增集团（启用状态）>
[2021-09-17 17:09:54,356] - logger.py] - ERROR: {"code":1,"msg":"手机号码已存在!","data":1}
[2021-09-17 17:09:54,361] - logger.py] - INFO: caseName: <客户集团详细信息>
[2021-09-17 17:09:54,573] - logger.py] - INFO: 断言结果：pass (0 == 0)
[2021-09-17 17:09:54,582] - logger.py] - INFO: caseName: <删除 客户集团信息>
[2021-09-17 17:09:55,038] - logger.py] - INFO: 断言结果：pass (0 == 0)
[2021-09-17 17:09:55,043] - logger.py] - INFO: caseName: <禁用-启用 客户集团信息>
[2021-09-17 17:09:55,488] - logger.py] - INFO: 断言结果：pass (0 == 0)
[2021-09-17 17:09:55,490] - logger.py] - INFO: --------接口自动化测试结束------------
[2021-09-17 17:11:22,379] - logger.py] - INFO: --------接口自动化测试开始------------
[2021-09-17 17:11:22,379] - logger.py] - INFO: caseName: <新增集团（启用状态）>
[2021-09-17 17:11:23,214] - logger.py] - INFO: 断言结果：pass (0 == 0)
[2021-09-17 17:11:23,289] - logger.py] - INFO: caseName: <客户集团详细信息>
[2021-09-17 17:11:23,469] - logger.py] - INFO: 断言结果：pass (0 == 0)
[2021-09-17 17:11:23,474] - logger.py] - INFO: caseName: <删除 客户集团信息>
[2021-09-17 17:11:23,929] - logger.py] - INFO: 断言结果：pass (0 == 0)
[2021-09-17 17:11:23,934] - logger.py] - INFO: caseName: <禁用-启用 客户集团信息>
[2021-09-17 17:11:24,288] - logger.py] - INFO: 断言结果：pass (0 == 0)
[2021-09-17 17:11:24,291] - logger.py] - INFO: --------接口自动化测试结束------------
[2021-09-17 17:11:40,642] - logger.py] - INFO: --------接口自动化测试开始------------
[2021-09-17 17:11:40,643] - logger.py] - INFO: caseName: <新增集团（启用状态）>
[2021-09-17 17:11:40,780] - logger.py] - ERROR: {"code":1,"msg":"手机号码已存在!","data":1}
[2021-09-17 17:11:40,783] - logger.py] - INFO: caseName: <客户集团详细信息>
[2021-09-17 17:11:40,886] - logger.py] - ERROR: {"code":1,"msg":"Failed to convert value of type 'java.lang.String' to required type 'java.lang.Long'; nested exception is java.lang.NumberFormatException: For input string: \"['809']\"","data":null}
[2021-09-17 17:11:40,891] - logger.py] - INFO: caseName: <删除 客户集团信息>
[2021-09-17 17:11:41,781] - logger.py] - INFO: 断言结果：pass (0 == 0)
[2021-09-17 17:11:41,786] - logger.py] - INFO: caseName: <禁用-启用 客户集团信息>
[2021-09-17 17:11:42,135] - logger.py] - INFO: 断言结果：pass (0 == 0)
[2021-09-17 17:11:42,138] - logger.py] - INFO: --------接口自动化测试结束------------
[2021-09-17 17:21:52,485] - logger.py] - INFO: --------接口自动化测试开始------------
[2021-09-17 17:21:52,486] - logger.py] - INFO: caseName: <新增集团（启用状态）>
[2021-09-17 17:21:53,104] - logger.py] - INFO: 断言结果：pass (0 == 0)
[2021-09-17 17:21:53,167] - logger.py] - INFO: caseName: <客户集团详细信息>
[2021-09-17 17:21:53,315] - logger.py] - ERROR: {"code":1,"msg":"无此客户！","data":1}
[2021-09-17 17:21:53,320] - logger.py] - INFO: caseName: <删除 客户集团信息>
[2021-09-17 17:21:53,608] - logger.py] - INFO: 断言结果：pass (0 == 0)
[2021-09-17 17:21:53,613] - logger.py] - INFO: caseName: <禁用-启用 客户集团信息>
[2021-09-17 17:21:54,121] - logger.py] - INFO: 断言结果：pass (0 == 0)
[2021-09-17 17:21:54,123] - logger.py] - INFO: --------接口自动化测试结束------------
[2021-09-17 17:22:05,793] - logger.py] - INFO: --------接口自动化测试开始------------
[2021-09-17 17:22:05,794] - logger.py] - INFO: caseName: <新增集团（启用状态）>
[2021-09-17 17:22:06,068] - logger.py] - ERROR: {"code":1,"msg":"手机号码已存在!","data":1}
[2021-09-17 17:22:06,072] - logger.py] - INFO: caseName: <客户集团详细信息>
[2021-09-17 17:22:06,206] - logger.py] - ERROR: {"code":1,"msg":"无此客户！","data":1}
[2021-09-17 17:22:06,209] - logger.py] - INFO: caseName: <删除 客户集团信息>
[2021-09-17 17:22:06,495] - logger.py] - INFO: 断言结果：pass (0 == 0)
[2021-09-17 17:22:06,498] - logger.py] - INFO: caseName: <禁用-启用 客户集团信息>
[2021-09-17 17:22:06,929] - logger.py] - INFO: 断言结果：pass (0 == 0)
[2021-09-17 17:22:06,931] - logger.py] - INFO: --------接口自动化测试结束------------
[2021-09-17 17:28:08,930] - logger.py] - INFO: --------接口自动化测试开始------------
[2021-09-17 17:28:08,931] - logger.py] - INFO: caseName: <新增集团（启用状态）>
[2021-09-17 17:28:09,525] - logger.py] - INFO: 断言结果：pass (0 == 0)
[2021-09-17 17:28:09,596] - logger.py] - INFO: caseName: <客户集团详细信息>
[2021-09-17 17:28:09,735] - logger.py] - ERROR: {"code":1,"msg":"无此客户！","data":1}
[2021-09-17 17:28:09,740] - logger.py] - INFO: caseName: <删除 客户集团信息>
[2021-09-17 17:28:10,034] - logger.py] - INFO: 断言结果：pass (0 == 0)
[2021-09-17 17:28:10,040] - logger.py] - INFO: caseName: <禁用-启用 客户集团信息>
[2021-09-17 17:28:10,445] - logger.py] - INFO: 断言结果：pass (0 == 0)
[2021-09-17 17:28:10,447] - logger.py] - INFO: --------接口自动化测试结束------------
[2021-09-17 17:30:56,011] - logger.py] - INFO: --------接口自动化测试开始------------
[2021-09-17 17:30:56,012] - logger.py] - INFO: caseName: <新增集团（启用状态）>
[2021-09-17 17:30:56,620] - logger.py] - INFO: 断言结果：pass (0 == 0)
[2021-09-17 17:30:56,685] - logger.py] - INFO: caseName: <客户集团详细信息>
[2021-09-17 17:30:56,909] - logger.py] - INFO: 断言结果：pass (0 == 0)
[2021-09-17 17:30:56,918] - logger.py] - INFO: caseName: <删除 客户集团信息>
[2021-09-17 17:30:57,109] - logger.py] - ERROR: {"code":1,"msg":"JSON parse error: Cannot deserialize instance of `java.lang.Long` out of START_ARRAY token; nested exception is com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot deserialize instance of `java.lang.Long` out of START_ARRAY token\n at [Source: (PushbackInputStream); line: 1, column: 8] (through reference chain: com.mkh.st.order.dto.IdDeleteDTO[\"id\"])","data":null}
[2021-09-17 17:30:57,110] - logger.py] - INFO: caseName: <禁用-启用 客户集团信息>
[2021-09-17 17:30:57,579] - logger.py] - INFO: 断言结果：pass (0 == 0)
[2021-09-17 17:30:57,582] - logger.py] - INFO: --------接口自动化测试结束------------
[2021-09-17 17:34:06,492] - logger.py] - INFO: --------接口自动化测试开始------------
[2021-09-17 17:34:06,493] - logger.py] - INFO: caseName: <新增集团（启用状态）>
[2021-09-17 17:34:06,632] - logger.py] - ERROR: {"code":1,"msg":"手机号码已存在!","data":1}
[2021-09-17 17:34:06,634] - logger.py] - INFO: caseName: <客户集团详细信息>
[2021-09-17 17:34:06,704] - logger.py] - ERROR: {"code":1,"msg":"Failed to convert value of type 'java.lang.String' to required type 'java.lang.Long'; nested exception is java.lang.NumberFormatException: For input string: \"['814']\"","data":null}
[2021-09-17 17:34:06,710] - logger.py] - INFO: caseName: <删除 客户集团信息>
[2021-09-17 17:34:06,780] - logger.py] - ERROR: {"code":1,"msg":"JSON parse error: Cannot deserialize instance of `java.lang.Long` out of START_ARRAY token; nested exception is com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot deserialize instance of `java.lang.Long` out of START_ARRAY token\n at [Source: (PushbackInputStream); line: 1, column: 8] (through reference chain: com.mkh.st.order.dto.IdDeleteDTO[\"id\"])","data":null}
[2021-09-17 17:34:06,782] - logger.py] - INFO: caseName: <禁用-启用 客户集团信息>
[2021-09-17 17:34:07,100] - logger.py] - INFO: 断言结果：pass (0 == 0)
[2021-09-17 17:34:07,102] - logger.py] - INFO: --------接口自动化测试结束------------
[2021-09-17 17:38:31,313] - logger.py] - INFO: --------接口自动化测试开始------------
[2021-09-17 17:38:31,313] - logger.py] - INFO: caseName: <新增集团（启用状态）>
[2021-09-17 17:38:31,483] - logger.py] - ERROR: {"code":1,"msg":"手机号码已存在!","data":1}
[2021-09-17 17:38:31,488] - logger.py] - INFO: caseName: <客户集团详细信息>
[2021-09-17 17:38:31,498] - logger.py] - WARNING: 出现如下异常:'NoneType' object has no attribute 'text'
[2021-09-17 17:38:31,503] - logger.py] - INFO: caseName: <删除 客户集团信息>
[2021-09-17 17:38:31,585] - logger.py] - ERROR: {"code":1,"msg":"JSON parse error: Cannot deserialize instance of `java.lang.Long` out of START_ARRAY token; nested exception is com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot deserialize instance of `java.lang.Long` out of START_ARRAY token\n at [Source: (PushbackInputStream); line: 1, column: 8] (through reference chain: com.mkh.st.order.dto.IdDeleteDTO[\"id\"])","data":null}
[2021-09-17 17:38:31,587] - logger.py] - INFO: caseName: <禁用-启用 客户集团信息>
[2021-09-17 17:38:31,885] - logger.py] - INFO: 断言结果：pass (0 == 0)
[2021-09-17 17:38:31,887] - logger.py] - INFO: --------接口自动化测试结束------------
[2021-09-17 17:39:36,463] - logger.py] - INFO: --------接口自动化测试开始------------
[2021-09-17 17:39:36,464] - logger.py] - INFO: caseName: <新增集团（启用状态）>
[2021-09-17 17:39:36,951] - logger.py] - INFO: 断言结果：pass (0 == 0)
[2021-09-17 17:39:37,008] - logger.py] - ERROR: {"code":0,"msg":null,"data":true}
[2021-09-17 17:39:37,015] - logger.py] - INFO: caseName: <客户集团详细信息>
[2021-09-17 17:39:37,024] - logger.py] - WARNING: 出现如下异常:'NoneType' object has no attribute 'text'
[2021-09-17 17:39:37,029] - logger.py] - INFO: caseName: <删除 客户集团信息>
[2021-09-17 17:39:37,133] - logger.py] - ERROR: {"code":1,"msg":"JSON parse error: Cannot deserialize instance of `java.lang.Long` out of START_ARRAY token; nested exception is com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot deserialize instance of `java.lang.Long` out of START_ARRAY token\n at [Source: (PushbackInputStream); line: 1, column: 8] (through reference chain: com.mkh.st.order.dto.IdDeleteDTO[\"id\"])","data":null}
[2021-09-17 17:39:37,138] - logger.py] - INFO: caseName: <禁用-启用 客户集团信息>
[2021-09-17 17:39:37,430] - logger.py] - INFO: 断言结果：pass (0 == 0)
[2021-09-17 17:39:37,432] - logger.py] - INFO: --------接口自动化测试结束------------
[2021-09-17 17:41:37,460] - logger.py] - INFO: --------接口自动化测试开始------------
[2021-09-17 17:41:37,460] - logger.py] - INFO: caseName: <新增集团（启用状态）>
[2021-09-17 17:41:37,603] - logger.py] - ERROR: {"code":1,"msg":"手机号码已存在!","data":1}
[2021-09-17 17:41:37,610] - logger.py] - INFO: caseName: <客户集团详细信息>
[2021-09-17 17:41:37,620] - logger.py] - WARNING: 出现如下异常:'NoneType' object has no attribute 'text'
[2021-09-17 17:41:37,626] - logger.py] - INFO: caseName: <删除 客户集团信息>
[2021-09-17 17:41:37,702] - logger.py] - ERROR: {"code":1,"msg":"JSON parse error: Cannot deserialize instance of `java.lang.Long` out of START_ARRAY token; nested exception is com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot deserialize instance of `java.lang.Long` out of START_ARRAY token\n at [Source: (PushbackInputStream); line: 1, column: 8] (through reference chain: com.mkh.st.order.dto.IdDeleteDTO[\"id\"])","data":null}
[2021-09-17 17:41:37,703] - logger.py] - INFO: caseName: <禁用-启用 客户集团信息>
[2021-09-17 17:41:37,986] - logger.py] - INFO: 断言结果：pass (0 == 0)
[2021-09-17 17:41:37,989] - logger.py] - INFO: --------接口自动化测试结束------------
[2021-09-17 17:42:29,844] - logger.py] - INFO: --------接口自动化测试开始------------
[2021-09-17 17:42:29,845] - logger.py] - INFO: caseName: <新增集团（启用状态）>
[2021-09-17 17:42:30,350] - logger.py] - INFO: 断言结果：pass (0 == 0)
[2021-09-17 17:42:30,416] - logger.py] - ERROR: {"code":0,"msg":null,"data":true}
[2021-09-17 17:42:30,422] - logger.py] - INFO: caseName: <客户集团详细信息>
[2021-09-17 17:42:30,431] - logger.py] - WARNING: 出现如下异常:'NoneType' object has no attribute 'text'
[2021-09-17 17:42:30,436] - logger.py] - INFO: caseName: <删除 客户集团信息>
[2021-09-17 17:42:30,517] - logger.py] - ERROR: {"code":1,"msg":"JSON parse error: Cannot deserialize instance of `java.lang.Long` out of START_ARRAY token; nested exception is com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot deserialize instance of `java.lang.Long` out of START_ARRAY token\n at [Source: (PushbackInputStream); line: 1, column: 8] (through reference chain: com.mkh.st.order.dto.IdDeleteDTO[\"id\"])","data":null}
[2021-09-17 17:42:30,522] - logger.py] - INFO: caseName: <禁用-启用 客户集团信息>
[2021-09-17 17:42:30,851] - logger.py] - INFO: 断言结果：pass (0 == 0)
[2021-09-17 17:42:30,853] - logger.py] - INFO: --------接口自动化测试结束------------
[2021-09-17 17:43:51,824] - logger.py] - INFO: --------接口自动化测试开始------------
[2021-09-17 17:43:51,825] - logger.py] - INFO: caseName: <新增集团（启用状态）>
[2021-09-17 17:43:51,985] - logger.py] - ERROR: {"code":1,"msg":"手机号码已存在!","data":1}
[2021-09-17 17:43:51,991] - logger.py] - INFO: caseName: <客户集团详细信息>
[2021-09-17 17:43:52,085] - logger.py] - ERROR: {"code":1,"msg":"Failed to convert value of type 'java.lang.String' to required type 'java.lang.Long'; nested exception is java.lang.NumberFormatException: For input string: \"['814']\"","data":null}
[2021-09-17 17:43:52,088] - logger.py] - INFO: caseName: <删除 客户集团信息>
[2021-09-17 17:43:52,164] - logger.py] - ERROR: {"code":1,"msg":"JSON parse error: Cannot deserialize instance of `java.lang.Long` out of START_ARRAY token; nested exception is com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot deserialize instance of `java.lang.Long` out of START_ARRAY token\n at [Source: (PushbackInputStream); line: 1, column: 8] (through reference chain: com.mkh.st.order.dto.IdDeleteDTO[\"id\"])","data":null}
[2021-09-17 17:43:52,165] - logger.py] - INFO: caseName: <禁用-启用 客户集团信息>
[2021-09-17 17:43:52,453] - logger.py] - INFO: 断言结果：pass (0 == 0)
[2021-09-17 17:43:52,455] - logger.py] - INFO: --------接口自动化测试结束------------
[2021-09-17 17:44:26,908] - logger.py] - INFO: --------接口自动化测试开始------------
[2021-09-17 17:44:26,909] - logger.py] - INFO: caseName: <新增集团（启用状态）>
[2021-09-17 17:44:27,480] - logger.py] - INFO: 断言结果：pass (0 == 0)
[2021-09-17 17:44:27,544] - logger.py] - ERROR: {"code":0,"msg":null,"data":true}
[2021-09-17 17:44:27,550] - logger.py] - INFO: caseName: <客户集团详细信息>
[2021-09-17 17:44:27,638] - logger.py] - ERROR: {"code":1,"msg":"Failed to convert value of type 'java.lang.String' to required type 'java.lang.Long'; nested exception is java.lang.NumberFormatException: For input string: \"['814']\"","data":null}
[2021-09-17 17:44:27,641] - logger.py] - INFO: caseName: <删除 客户集团信息>
[2021-09-17 17:44:27,725] - logger.py] - ERROR: {"code":1,"msg":"JSON parse error: Cannot deserialize instance of `java.lang.Long` out of START_ARRAY token; nested exception is com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot deserialize instance of `java.lang.Long` out of START_ARRAY token\n at [Source: (PushbackInputStream); line: 1, column: 8] (through reference chain: com.mkh.st.order.dto.IdDeleteDTO[\"id\"])","data":null}
[2021-09-17 17:44:27,731] - logger.py] - INFO: caseName: <禁用-启用 客户集团信息>
[2021-09-17 17:44:28,076] - logger.py] - INFO: 断言结果：pass (0 == 0)
[2021-09-17 17:44:28,078] - logger.py] - INFO: --------接口自动化测试结束------------
[2021-09-17 17:45:07,168] - logger.py] - INFO: --------接口自动化测试开始------------
[2021-09-17 17:45:07,168] - logger.py] - INFO: caseName: <新增集团（启用状态）>
[2021-09-17 17:45:07,527] - logger.py] - ERROR: {"code":1,"msg":"手机号码已存在!","data":1}
[2021-09-17 17:45:07,528] - logger.py] - INFO: caseName: <客户集团详细信息>
[2021-09-17 17:45:07,717] - logger.py] - ERROR: {"code":1,"msg":"Failed to convert value of type 'java.lang.String' to required type 'java.lang.Long'; nested exception is java.lang.NumberFormatException: For input string: \"['814']\"","data":null}
[2021-09-17 17:45:07,722] - logger.py] - INFO: caseName: <删除 客户集团信息>
[2021-09-17 17:45:07,989] - logger.py] - ERROR: {"code":1,"msg":"JSON parse error: Cannot deserialize instance of `java.lang.Long` out of START_ARRAY token; nested exception is com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot deserialize instance of `java.lang.Long` out of START_ARRAY token\n at [Source: (PushbackInputStream); line: 1, column: 8] (through reference chain: com.mkh.st.order.dto.IdDeleteDTO[\"id\"])","data":null}
[2021-09-17 17:45:07,994] - logger.py] - INFO: caseName: <禁用-启用 客户集团信息>
[2021-09-17 17:45:08,370] - logger.py] - INFO: 断言结果：pass (0 == 0)
[2021-09-17 17:45:08,372] - logger.py] - INFO: --------接口自动化测试结束------------
[2021-09-17 17:45:55,998] - logger.py] - INFO: --------接口自动化测试开始------------
[2021-09-17 17:45:55,998] - logger.py] - INFO: caseName: <新增集团（启用状态）>
[2021-09-17 17:45:56,489] - logger.py] - INFO: 断言结果：pass (0 == 0)
[2021-09-17 17:45:56,550] - logger.py] - ERROR: {"code":0,"msg":null,"data":true}
[2021-09-17 17:45:56,557] - logger.py] - INFO: caseName: <客户集团详细信息>
[2021-09-17 17:45:56,559] - logger.py] - ERROR: {"code":0,"msg":null,"data":true}
[2021-09-17 17:45:56,564] - logger.py] - INFO: caseName: <删除 客户集团信息>
[2021-09-17 17:45:56,566] - logger.py] - ERROR: {"code":0,"msg":null,"data":true}
[2021-09-17 17:45:56,571] - logger.py] - INFO: caseName: <禁用-启用 客户集团信息>
[2021-09-17 17:45:56,573] - logger.py] - ERROR: {"code":0,"msg":null,"data":true}
[2021-09-17 17:45:56,575] - logger.py] - INFO: --------接口自动化测试结束------------
[2021-09-17 17:53:14,122] - logger.py] - INFO: --------接口自动化测试开始------------
[2021-09-17 17:53:14,123] - logger.py] - INFO: caseName: <新增集团（启用状态）>
[2021-09-17 17:53:14,277] - logger.py] - ERROR: {"code":1,"msg":"手机号码已存在!","data":1}
[2021-09-17 17:53:14,280] - logger.py] - INFO: caseName: <客户集团详细信息>
[2021-09-17 17:53:14,281] - logger.py] - ERROR: {"code":1,"msg":"手机号码已存在!","data":1}
[2021-09-17 17:53:14,283] - logger.py] - INFO: caseName: <删除 客户集团信息>
[2021-09-17 17:53:14,284] - logger.py] - ERROR: {"code":1,"msg":"手机号码已存在!","data":1}
[2021-09-17 17:53:14,288] - logger.py] - INFO: caseName: <禁用-启用 客户集团信息>
[2021-09-17 17:53:14,289] - logger.py] - ERROR: {"code":1,"msg":"手机号码已存在!","data":1}
[2021-09-17 17:53:14,290] - logger.py] - INFO: --------接口自动化测试结束------------
[2021-09-17 17:53:47,575] - logger.py] - INFO: --------接口自动化测试开始------------
[2021-09-17 17:53:47,576] - logger.py] - INFO: caseName: <新增集团（启用状态）>
[2021-09-17 17:53:48,047] - logger.py] - INFO: 断言结果：pass (0 == 0)
[2021-09-17 17:53:48,101] - logger.py] - INFO: caseName: <客户集团详细信息>
[2021-09-17 17:53:48,272] - logger.py] - INFO: 断言结果：pass (0 == 0)
[2021-09-17 17:53:48,280] - logger.py] - INFO: caseName: <删除 客户集团信息>
[2021-09-17 17:53:48,382] - logger.py] - ERROR: {"code":1,"msg":"JSON parse error: Cannot deserialize instance of `java.lang.Long` out of START_ARRAY token; nested exception is com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot deserialize instance of `java.lang.Long` out of START_ARRAY token\n at [Source: (PushbackInputStream); line: 1, column: 8] (through reference chain: com.mkh.st.order.dto.IdDeleteDTO[\"id\"])","data":null}
[2021-09-17 17:53:48,387] - logger.py] - INFO: caseName: <禁用-启用 客户集团信息>
[2021-09-17 17:53:48,719] - logger.py] - INFO: 断言结果：pass (0 == 0)
[2021-09-17 17:53:48,722] - logger.py] - INFO: --------接口自动化测试结束------------
[2021-09-17 17:54:07,050] - logger.py] - INFO: --------接口自动化测试开始------------
[2021-09-17 17:54:07,051] - logger.py] - INFO: caseName: <新增集团（启用状态）>
[2021-09-17 17:54:07,234] - logger.py] - ERROR: {"code":1,"msg":"手机号码已存在!","data":1}
[2021-09-17 17:54:07,239] - logger.py] - INFO: caseName: <客户集团详细信息>
[2021-09-17 17:54:07,327] - logger.py] - ERROR: {"code":1,"msg":"Failed to convert value of type 'java.lang.String' to required type 'java.lang.Long'; nested exception is java.lang.NumberFormatException: For input string: \"['819']\"","data":null}
[2021-09-17 17:54:07,333] - logger.py] - INFO: caseName: <删除 客户集团信息>
[2021-09-17 17:54:07,419] - logger.py] - ERROR: {"code":1,"msg":"JSON parse error: Cannot deserialize instance of `java.lang.Long` out of START_ARRAY token; nested exception is com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot deserialize instance of `java.lang.Long` out of START_ARRAY token\n at [Source: (PushbackInputStream); line: 1, column: 8] (through reference chain: com.mkh.st.order.dto.IdDeleteDTO[\"id\"])","data":null}
[2021-09-17 17:54:07,424] - logger.py] - INFO: caseName: <禁用-启用 客户集团信息>
[2021-09-17 17:54:07,729] - logger.py] - INFO: 断言结果：pass (0 == 0)
[2021-09-17 17:54:07,730] - logger.py] - INFO: --------接口自动化测试结束------------
[2021-09-17 17:55:57,886] - logger.py] - INFO: --------接口自动化测试开始------------
[2021-09-17 17:55:57,887] - logger.py] - INFO: caseName: <新增集团（启用状态）>
[2021-09-17 17:55:58,029] - logger.py] - ERROR: {"code":1,"msg":"手机号码已存在!","data":1}
[2021-09-17 17:55:58,034] - logger.py] - INFO: caseName: <客户集团详细信息>
[2021-09-17 17:55:58,120] - logger.py] - ERROR: {"code":1,"msg":"Failed to convert value of type 'java.lang.String' to required type 'java.lang.Long'; nested exception is java.lang.NumberFormatException: For input string: \"['819']\"","data":null}
[2021-09-17 17:55:58,125] - logger.py] - INFO: caseName: <禁用-启用 客户集团信息>
[2021-09-17 17:55:58,473] - logger.py] - INFO: 断言结果：pass (0 == 0)
[2021-09-17 17:55:58,475] - logger.py] - INFO: --------接口自动化测试结束------------
[2021-09-17 17:56:10,711] - logger.py] - INFO: --------接口自动化测试开始------------
[2021-09-17 17:56:10,711] - logger.py] - INFO: caseName: <新增集团（启用状态）>
[2021-09-17 17:56:10,856] - logger.py] - ERROR: {"code":1,"msg":"手机号码已存在!","data":1}
[2021-09-17 17:56:10,859] - logger.py] - INFO: caseName: <客户集团详细信息>
[2021-09-17 17:56:10,941] - logger.py] - ERROR: {"code":1,"msg":"Failed to convert value of type 'java.lang.String' to required type 'java.lang.Long'; nested exception is java.lang.NumberFormatException: For input string: \"[819]\"","data":null}
[2021-09-17 17:56:10,946] - logger.py] - INFO: caseName: <禁用-启用 客户集团信息>
[2021-09-17 17:56:11,260] - logger.py] - INFO: 断言结果：pass (0 == 0)
[2021-09-17 17:56:11,262] - logger.py] - INFO: --------接口自动化测试结束------------
[2021-09-17 17:57:05,083] - logger.py] - INFO: --------接口自动化测试开始------------
[2021-09-17 17:57:05,084] - logger.py] - INFO: caseName: <新增集团（启用状态）>
[2021-09-17 17:57:05,692] - logger.py] - INFO: 断言结果：pass (0 == 0)
[2021-09-17 17:57:05,745] - logger.py] - INFO: caseName: <客户集团详细信息>
[2021-09-17 17:57:05,994] - logger.py] - INFO: 断言结果：pass (0 == 0)
[2021-09-17 17:57:06,002] - logger.py] - INFO: caseName: <禁用-启用 客户集团信息>
[2021-09-17 17:57:06,552] - logger.py] - INFO: 断言结果：pass (0 == 0)
[2021-09-17 17:57:06,555] - logger.py] - INFO: --------接口自动化测试结束------------
[2021-09-17 17:58:18,865] - logger.py] - INFO: --------接口自动化测试开始------------
[2021-09-17 17:58:18,865] - logger.py] - INFO: caseName: <新增集团（启用状态）>
[2021-09-17 17:58:19,352] - logger.py] - INFO: 断言结果：pass (0 == 0)
[2021-09-17 17:58:19,426] - logger.py] - INFO: caseName: <客户集团详细信息>
[2021-09-17 17:58:19,600] - logger.py] - INFO: 断言结果：pass (0 == 0)
[2021-09-17 17:58:19,605] - logger.py] - INFO: caseName: <禁用-启用 客户集团信息>
[2021-09-17 17:58:19,907] - logger.py] - INFO: 断言结果：pass (0 == 0)
[2021-09-17 17:58:19,910] - logger.py] - INFO: --------接口自动化测试结束------------
[2021-09-17 17:58:43,512] - logger.py] - INFO: --------接口自动化测试开始------------
[2021-09-17 17:58:43,513] - logger.py] - INFO: caseName: <新增集团（启用状态）>
[2021-09-17 17:58:43,638] - logger.py] - ERROR: {"code":1,"msg":"手机号码已存在!","data":1}
[2021-09-17 17:58:43,639] - logger.py] - INFO: caseName: <客户集团详细信息>
[2021-09-17 17:58:43,709] - logger.py] - ERROR: {"code":1,"msg":"Failed to convert value of type 'java.lang.String' to required type 'java.lang.Long'; nested exception is java.lang.NumberFormatException: For input string: \"['821']\"","data":null}
[2021-09-17 17:58:43,711] - logger.py] - INFO: caseName: <禁用-启用 客户集团信息>
[2021-09-17 17:58:44,022] - logger.py] - INFO: 断言结果：pass (0 == 0)
[2021-09-17 17:58:44,024] - logger.py] - INFO: --------接口自动化测试结束------------
[2021-09-17 18:43:41,546] - logger.py] - INFO: --------接口自动化测试开始------------
[2021-09-17 18:43:41,547] - logger.py] - INFO: caseName: <新增集团（启用状态）>
[2021-09-17 18:43:41,577] - logger.py] - ERROR: {"code":1,"msg":"503 SERVICE_UNAVAILABLE \"No instance available for st-order-admin-biz\"","data":null}
[2021-09-17 18:43:41,578] - logger.py] - INFO: caseName: <禁用-启用 客户集团信息>
[2021-09-17 18:43:41,628] - logger.py] - ERROR: {"code":1,"msg":"503 SERVICE_UNAVAILABLE \"No instance available for st-order-admin-biz\"","data":null}
[2021-09-17 18:43:41,629] - logger.py] - INFO: --------接口自动化测试结束------------
[2021-09-17 18:44:27,522] - logger.py] - INFO: --------接口自动化测试开始------------
[2021-09-17 18:44:27,522] - logger.py] - INFO: caseName: <新增集团（启用状态）>
[2021-09-17 18:44:28,197] - logger.py] - ERROR: {"code":1,"msg":"手机号码已存在!","data":1}
[2021-09-17 18:44:28,203] - logger.py] - INFO: caseName: <禁用-启用 客户集团信息>
[2021-09-17 18:44:28,608] - logger.py] - INFO: 断言结果：pass (0 == 0)
[2021-09-17 18:44:28,609] - logger.py] - INFO: --------接口自动化测试结束------------
[2021-09-17 18:45:26,490] - logger.py] - INFO: --------接口自动化测试开始------------
[2021-09-17 18:45:26,491] - logger.py] - INFO: caseName: <新增集团（启用状态）>
[2021-09-17 18:45:27,067] - logger.py] - INFO: 断言结果：pass (0 == 0)
[2021-09-17 18:45:27,129] - logger.py] - INFO: caseName: <禁用-启用 客户集团信息>
[2021-09-17 18:45:27,484] - logger.py] - INFO: 断言结果：pass (0 == 0)
[2021-09-17 18:45:27,485] - logger.py] - INFO: --------接口自动化测试结束------------
[2021-09-17 18:53:25,976] - logger.py] - INFO: --------接口自动化测试开始------------
[2021-09-17 18:53:25,977] - logger.py] - INFO: caseName: <新增集团（启用状态）>
[2021-09-17 18:53:26,196] - logger.py] - ERROR: {"code":1,"msg":"手机号码已存在!","data":1}
[2021-09-17 18:53:26,202] - logger.py] - INFO: caseName: <客户集团详细信息>
[2021-09-17 18:53:26,354] - logger.py] - INFO: 断言结果：pass (0 == 0)
[2021-09-17 18:53:26,356] - logger.py] - INFO: caseName: <禁用-启用 客户集团信息>
[2021-09-17 18:53:26,664] - logger.py] - INFO: 断言结果：pass (0 == 0)
[2021-09-17 18:53:26,666] - logger.py] - INFO: --------接口自动化测试结束------------
[2021-09-17 18:53:57,803] - logger.py] - INFO: --------接口自动化测试开始------------
[2021-09-17 18:53:57,803] - logger.py] - INFO: caseName: <新增集团（启用状态）>
[2021-09-17 18:53:57,936] - logger.py] - ERROR: {"code":1,"msg":"手机号码已存在!","data":1}
[2021-09-17 18:53:57,941] - logger.py] - INFO: caseName: <客户集团详细信息>
[2021-09-17 18:53:58,086] - logger.py] - INFO: 断言结果：pass (0 == 0)
[2021-09-17 18:53:58,091] - logger.py] - INFO: caseName: <禁用-启用 客户集团信息>
[2021-09-17 18:53:58,433] - logger.py] - INFO: 断言结果：pass (0 == 0)
[2021-09-17 18:53:58,434] - logger.py] - INFO: --------接口自动化测试结束------------
[2021-09-17 18:57:23,302] - logger.py] - INFO: --------接口自动化测试开始------------
[2021-09-17 18:57:23,302] - logger.py] - INFO: caseName: <新增集团（启用状态）>
[2021-09-17 18:57:24,448] - logger.py] - ERROR: {"code":1,"msg":"手机号码已存在!","data":1}
[2021-09-17 18:57:24,454] - logger.py] - INFO: caseName: <客户集团详细信息>
[2021-09-17 18:57:25,102] - logger.py] - INFO: 断言结果：pass (0 == 0)
[2021-09-17 18:57:25,111] - logger.py] - INFO: caseName: <禁用-启用 客户集团信息>
[2021-09-17 18:57:25,350] - logger.py] - INFO: 断言结果：pass (0 == 0)
[2021-09-17 18:57:25,352] - logger.py] - INFO: --------接口自动化测试结束------------
[2021-09-17 18:57:34,232] - logger.py] - INFO: --------接口自动化测试开始------------
[2021-09-17 18:57:34,232] - logger.py] - INFO: caseName: <新增集团（启用状态）>
[2021-09-17 18:57:34,361] - logger.py] - ERROR: {"code":1,"msg":"手机号码已存在!","data":1}
[2021-09-17 18:57:34,363] - logger.py] - INFO: caseName: <客户集团详细信息>
[2021-09-17 18:57:34,445] - logger.py] - ERROR: {"code":1,"msg":"Failed to convert value of type 'java.lang.String' to required type 'java.lang.Long'; nested exception is java.lang.NumberFormatException: For input string: \"['822']\"","data":null}
[2021-09-17 18:57:34,450] - logger.py] - INFO: caseName: <禁用-启用 客户集团信息>
[2021-09-17 18:57:34,696] - logger.py] - INFO: 断言结果：pass (0 == 0)
[2021-09-17 18:57:34,698] - logger.py] - INFO: --------接口自动化测试结束------------
[2021-09-17 18:57:58,082] - logger.py] - INFO: --------接口自动化测试开始------------
[2021-09-17 18:57:58,083] - logger.py] - INFO: caseName: <新增集团（启用状态）>
[2021-09-17 18:57:58,206] - logger.py] - ERROR: {"code":1,"msg":"手机号码已存在!","data":1}
[2021-09-17 18:57:58,207] - logger.py] - INFO: caseName: <客户集团详细信息>
[2021-09-17 18:57:58,277] - logger.py] - ERROR: {"code":1,"msg":"Failed to convert value of type 'java.lang.String' to required type 'java.lang.Long'; nested exception is java.lang.NumberFormatException: For input string: \"['822']\"","data":null}
[2021-09-17 18:57:58,281] - logger.py] - INFO: caseName: <禁用-启用 客户集团信息>
[2021-09-17 18:57:58,639] - logger.py] - INFO: 断言结果：pass (0 == 0)
[2021-09-17 18:57:58,642] - logger.py] - INFO: --------接口自动化测试结束------------
[2021-09-17 18:58:20,509] - logger.py] - INFO: --------接口自动化测试开始------------
[2021-09-17 18:58:20,510] - logger.py] - INFO: caseName: <新增集团（启用状态）>
[2021-09-17 18:58:20,606] - logger.py] - ERROR: {"code":1,"msg":"手机号码已存在!","data":1}
[2021-09-17 18:58:20,611] - logger.py] - INFO: caseName: <客户集团详细信息>
[2021-09-17 18:58:20,679] - logger.py] - ERROR: {"code":1,"msg":"Failed to convert value of type 'java.lang.String' to required type 'java.lang.Long'; nested exception is java.lang.NumberFormatException: For input string: \"[822]\"","data":null}
[2021-09-17 18:58:20,682] - logger.py] - INFO: caseName: <禁用-启用 客户集团信息>
[2021-09-17 18:58:20,955] - logger.py] - INFO: 断言结果：pass (0 == 0)
[2021-09-17 18:58:20,957] - logger.py] - INFO: --------接口自动化测试结束------------
[2021-09-17 19:00:20,547] - logger.py] - INFO: --------接口自动化测试开始------------
[2021-09-17 19:00:20,548] - logger.py] - INFO: caseName: <新增集团（启用状态）>
[2021-09-17 19:00:20,645] - logger.py] - ERROR: {"code":1,"msg":"手机号码已存在!","data":1}
[2021-09-17 19:00:20,650] - logger.py] - INFO: caseName: <客户集团详细信息>
[2021-09-17 19:00:20,725] - logger.py] - ERROR: {"code":1,"msg":"Failed to convert value of type 'java.lang.String' to required type 'java.lang.Long'; nested exception is java.lang.NumberFormatException: For input string: \"[822]\"","data":null}
[2021-09-17 19:00:20,730] - logger.py] - INFO: caseName: <禁用-启用 客户集团信息>
[2021-09-17 19:00:20,957] - logger.py] - INFO: 断言结果：pass (0 == 0)
[2021-09-17 19:00:20,959] - logger.py] - INFO: --------接口自动化测试结束------------
[2021-09-17 19:00:48,457] - logger.py] - INFO: --------接口自动化测试开始------------
[2021-09-17 19:00:48,458] - logger.py] - INFO: caseName: <新增集团（启用状态）>
[2021-09-17 19:00:49,217] - logger.py] - INFO: 断言结果：pass (0 == 0)
[2021-09-17 19:00:49,284] - logger.py] - INFO: caseName: <客户集团详细信息>
[2021-09-17 19:00:49,449] - logger.py] - INFO: 断言结果：pass (0 == 0)
[2021-09-17 19:00:49,457] - logger.py] - INFO: caseName: <禁用-启用 客户集团信息>
[2021-09-17 19:00:49,693] - logger.py] - INFO: 断言结果：pass (0 == 0)
[2021-09-17 19:00:49,695] - logger.py] - INFO: --------接口自动化测试结束------------
[2021-09-17 19:01:21,101] - logger.py] - INFO: --------接口自动化测试开始------------
[2021-09-17 19:01:21,101] - logger.py] - INFO: caseName: <新增集团（启用状态）>
[2021-09-17 19:01:21,605] - logger.py] - INFO: 断言结果：pass (0 == 0)
[2021-09-17 19:01:21,649] - logger.py] - INFO: caseName: <客户集团详细信息>
[2021-09-17 19:01:21,753] - logger.py] - INFO: 断言结果：pass (0 == 0)
[2021-09-17 19:01:21,756] - logger.py] - INFO: caseName: <禁用-启用 客户集团信息>
[2021-09-17 19:01:21,926] - logger.py] - INFO: 断言结果：pass (0 == 0)
[2021-09-17 19:01:21,927] - logger.py] - INFO: --------接口自动化测试结束------------
[2021-09-17 19:01:37,699] - logger.py] - INFO: --------接口自动化测试开始------------
[2021-09-17 19:01:37,700] - logger.py] - INFO: caseName: <新增集团（启用状态）>
[2021-09-17 19:01:37,797] - logger.py] - ERROR: {"code":1,"msg":"手机号码已存在!","data":1}
[2021-09-17 19:01:37,800] - logger.py] - INFO: caseName: <客户集团详细信息>
[2021-09-17 19:01:37,929] - logger.py] - INFO: 断言结果：pass (0 == 0)
[2021-09-17 19:01:37,937] - logger.py] - INFO: caseName: <禁用-启用 客户集团信息>
[2021-09-17 19:01:38,133] - logger.py] - INFO: 断言结果：pass (0 == 0)
[2021-09-17 19:01:38,135] - logger.py] - INFO: --------接口自动化测试结束------------
[2021-09-17 19:01:44,771] - logger.py] - INFO: --------接口自动化测试开始------------
[2021-09-17 19:01:44,771] - logger.py] - INFO: caseName: <新增集团（启用状态）>
[2021-09-17 19:01:44,862] - logger.py] - ERROR: {"code":1,"msg":"手机号码已存在!","data":1}
[2021-09-17 19:01:44,864] - logger.py] - INFO: caseName: <客户集团详细信息>
[2021-09-17 19:01:44,969] - logger.py] - INFO: 断言结果：pass (0 == 0)
[2021-09-17 19:01:44,973] - logger.py] - INFO: caseName: <禁用-启用 客户集团信息>
[2021-09-17 19:01:45,162] - logger.py] - INFO: 断言结果：pass (0 == 0)
[2021-09-17 19:01:45,163] - logger.py] - INFO: --------接口自动化测试结束------------
[2021-09-17 19:02:02,973] - logger.py] - INFO: --------接口自动化测试开始------------
[2021-09-17 19:02:02,974] - logger.py] - INFO: caseName: <新增集团（启用状态）>
[2021-09-17 19:02:03,076] - logger.py] - ERROR: {"code":1,"msg":"手机号码已存在!","data":1}
[2021-09-17 19:02:03,080] - logger.py] - INFO: caseName: <客户集团详细信息>
[2021-09-17 19:02:03,206] - logger.py] - INFO: 断言结果：pass (0 == 0)
[2021-09-17 19:02:03,210] - logger.py] - INFO: caseName: <禁用-启用 客户集团信息>
[2021-09-17 19:02:03,395] - logger.py] - INFO: 断言结果：pass (0 == 0)
[2021-09-17 19:02:03,396] - logger.py] - INFO: --------接口自动化测试结束------------
[2021-09-17 19:02:25,130] - logger.py] - INFO: --------接口自动化测试开始------------
[2021-09-17 19:02:25,130] - logger.py] - INFO: caseName: <新增集团（启用状态）>
[2021-09-17 19:02:25,218] - logger.py] - ERROR: {"code":1,"msg":"手机号码已存在!","data":1}
[2021-09-17 19:02:25,223] - logger.py] - INFO: caseName: <客户集团详细信息>
[2021-09-17 19:02:25,346] - logger.py] - INFO: 断言结果：pass (0 == 0)
[2021-09-17 19:02:25,354] - logger.py] - INFO: caseName: <删除 客户集团信息>
[2021-09-17 19:02:25,616] - logger.py] - INFO: 断言结果：pass (0 == 0)
[2021-09-17 19:02:25,621] - logger.py] - INFO: caseName: <禁用-启用 客户集团信息>
[2021-09-17 19:02:25,838] - logger.py] - INFO: 断言结果：pass (0 == 0)
[2021-09-17 19:02:25,840] - logger.py] - INFO: --------接口自动化测试结束------------
[2021-09-17 19:02:37,211] - logger.py] - INFO: --------接口自动化测试开始------------
[2021-09-17 19:02:37,212] - logger.py] - INFO: caseName: <新增集团（启用状态）>
[2021-09-17 19:02:37,624] - logger.py] - INFO: 断言结果：pass (0 == 0)
[2021-09-17 19:02:37,679] - logger.py] - INFO: caseName: <客户集团详细信息>
[2021-09-17 19:02:37,829] - logger.py] - INFO: 断言结果：pass (0 == 0)
[2021-09-17 19:02:37,837] - logger.py] - INFO: caseName: <删除 客户集团信息>
[2021-09-17 19:02:38,160] - logger.py] - INFO: 断言结果：pass (0 == 0)
[2021-09-17 19:02:38,166] - logger.py] - INFO: caseName: <禁用-启用 客户集团信息>
[2021-09-17 19:02:38,389] - logger.py] - INFO: 断言结果：pass (0 == 0)
[2021-09-17 19:02:38,390] - logger.py] - INFO: --------接口自动化测试结束------------
[2021-09-17 19:02:43,721] - logger.py] - INFO: --------接口自动化测试开始------------
[2021-09-17 19:02:43,721] - logger.py] - INFO: caseName: <新增集团（启用状态）>
[2021-09-17 19:02:44,156] - logger.py] - INFO: 断言结果：pass (0 == 0)
[2021-09-17 19:02:44,215] - logger.py] - INFO: caseName: <客户集团详细信息>
[2021-09-17 19:02:44,357] - logger.py] - INFO: 断言结果：pass (0 == 0)
[2021-09-17 19:02:44,365] - logger.py] - INFO: caseName: <删除 客户集团信息>
[2021-09-17 19:02:44,575] - logger.py] - INFO: 断言结果：pass (0 == 0)
[2021-09-17 19:02:44,580] - logger.py] - INFO: caseName: <禁用-启用 客户集团信息>
[2021-09-17 19:02:44,756] - logger.py] - INFO: 断言结果：pass (0 == 0)
[2021-09-17 19:02:44,758] - logger.py] - INFO: --------接口自动化测试结束------------
